#!/usr/bin/env node
/* freeze_tips.mjs — freeze each game's tip BEFORE kick-off, server-side.
 *
 * WHY THIS EXISTS: full-time grading must never grade a recomputed tip — after a
 * game, the Elo already contains that game's result and the market price is gone,
 * so the "tip" can flip to the winner with hindsight (see docs/GOTCHAS.md,
 * 2026-08-02). Grading therefore reads a frozen pre-kick-off tip. Freezing it in
 * the browser (localStorage) worked but was per-device; THIS script freezes it in
 * the pipeline instead, so every device sees the same record, automatically.
 *
 * HOW: it does NOT reimplement the model (a Python mirror is exactly the drift
 * risk GOTCHAS.md warns about). It loads the real nrl-tipping-guide.html with the
 * freshly generated data files into jsdom and asks the page's own predict() /
 * tipSide() what it is telling users right now. Zero divergence by construction:
 * if the front-end model changes, this freezes the changed model's tips.
 *
 * Output: nrl_tiplog.js -> window.NRL_TIPLOG = { updated, tips: [
 *   {season, round, home, away, tip, ko, ts}, ... ] }
 * An entry is (re)written on every run while its kick-off is still in the
 * future — the last pre-kick-off run wins. Once the game starts the entry is
 * never touched again. Entries for past rounds are kept (the season's record);
 * the log is pruned to the newest 250 entries. Best-effort: any failure leaves
 * the committed file untouched and exits 0 (a missing freeze must never block a
 * publish — the front-end falls back to its localStorage snapshot + the lock rule).
 */
import fs from 'fs';
import { JSDOM } from 'jsdom';

const PAGE = 'nrl-tipping-guide.html';
const OUT  = 'nrl_tiplog.js';
const DATA = ['nrl_data.js', 'nrl_learned.js', 'nrl_players.js', 'nrl_lineups.js'];

function readTiplog() {
  try {
    const raw = fs.readFileSync(OUT, 'utf8');
    const m = raw.match(/window\.NRL_TIPLOG\s*=\s*(\{[\s\S]*\})\s*;?\s*$/);
    const d = JSON.parse(m[1]);
    return Array.isArray(d.tips) ? d.tips : [];
  } catch (e) { return []; }
}

function main() {
  let html = fs.readFileSync(PAGE, 'utf8');
  // Inline the data files in place of their <script src> tags so the page runs
  // exactly as deployed, against exactly this run's data.
  for (const f of DATA) {
    const tag = new RegExp(`<script src="${f.replace('.', '\\.')}"></script>`);
    const body = fs.existsSync(f) ? fs.readFileSync(f, 'utf8') : '';
    html = html.replace(tag, `<script>${body}</script>`);
  }
  // The tip log itself must NOT load into this evaluation (it isn't needed and
  // keeps the freeze independent of its own output).
  html = html.replace(/<script src="nrl_tiplog\.js"><\/script>/, '');

  const dom = new JSDOM(html, {
    url: 'https://localhost/', runScripts: 'dangerously', pretendToBeVisual: true,
  });
  const w = dom.window;

  // Ask the page what it is tipping for every game that hasn't kicked off.
  const fresh = w.eval(`(function(){
    const out=[];
    fixtures.forEach(f=>{
      if(!T(f.home)||!T(f.away)) return;
      const p=predict(f);
      if(fixtureResult(p)) return;                      // already has a score
      const ko=f.kickoff?Date.parse(f.kickoff):NaN;
      if(!isNaN(ko) && Date.now()>=ko) return;          // under way — too late
      out.push({season:SRC.season, round:SRC.round, home:f.home, away:f.away,
                tip:tipSide(p).short, ko:f.kickoff||null});
    });
    return out;
  })()`);

  const now = new Date().toISOString();
  const log = readTiplog();
  const key = (t) => `${t.season}-${t.round}-${t.home}-${t.away}`;
  const byKey = {};
  log.forEach((t) => { byKey[key(t)] = t; });
  let changed = 0;
  fresh.forEach((t) => {
    const k = key(t);
    const cur = byKey[k];
    if (!cur || cur.tip !== t.tip) changed++;
    byKey[k] = { ...t, ts: now };            // pre-kick-off: last run wins
  });
  let tips = Object.values(byKey);
  tips.sort((a, b) => (a.season - b.season) || (a.round - b.round) || a.home.localeCompare(b.home));
  if (tips.length > 250) tips = tips.slice(tips.length - 250);

  const out = `/* Auto-generated by freeze_tips.mjs — DO NOT hand-edit (overwritten each run).
 * The official pre-kick-off tip for each game, frozen by the pipeline so
 * full-time grading is identical on every device and can never use hindsight.
 * An entry stops changing the moment its game kicks off. */
window.NRL_TIPLOG = ${JSON.stringify({ updated: now, tips }, null, 1)};
`;
  const tmp = OUT + '.tmp';
  fs.writeFileSync(tmp, out);
  fs.renameSync(tmp, OUT);
  console.log(`[freeze_tips] froze ${fresh.length} upcoming tip(s) (${changed} new/changed), log now ${tips.length} entries.`);
}

try { main(); }
catch (e) {
  console.error(`[freeze_tips] WARNING: freeze failed (${e && e.message}) — keeping the committed ${OUT}; front-end falls back to local snapshots + the lock rule.`);
  process.exit(0);   // best-effort by design: never block a publish
}
