/* rebuilt by cloud_fetch.py from the live Zero Tackle team lists.
   The named squad per club for the round below. The front-end uses this to
   cancel an injury-table entry for a player who is actually named in the
   side — without it, a season-long 'TBC' keeps a fit player half-out
   forever. Empty/stale is safe: the model just falls back to the
   injury table alone. */
window.NRL_LINEUPS = {
  "round": 22,
  "teams": {
    "BRI": ["Reece Walsh", "Josiah Karapani", "Kotoni Staggs", "Deine Mariner", "Grant Anderson", "Ezra Mam", "Adam Reynolds", "Va'a Semu", "Vaa Semu", "Cory Paix", "Payne Haas", "Xavier Willison", "Jordan Riki", "Patrick Carrigan", "Billy Walters", "Ben Talty", "Jaiyden Hunt", "Ben Hunt", "Luke Gale", "Luke Gale 2", "Hayze Perham"],
    "CAN": ["Connor Tracey", "Jacob Kiraz", "Matt Burton", "Enari Tuala", "Jethro Rinakama", "Stephen Crichton", "Lachlan Galvin", "Max King", "Bailey Hayward", "Leo Thompson", "Viliame Kikau", "Jacob Preston", "Jaeman Salmon", "Kurt Mann", "Josh Curran", "Harry Hayes", "Alekolasimi Jones", "Jed Reardon", "Sean O'Sullivan", "Sean Osullivan"],
    "CBR": ["Kaeo Weekes", "Jed Stuart", "Simi Sasagi", "Matthew Timoko", "Xavier Savage", "Ethan Strange", "Ethan Sanders", "Corey Horsburgh", "Owen Pattie", "Joseph Tapine", "Zac Hosking", "Ata Mariota", "Morgan Smithies", "Tom Starling", "Matty Nicholson", "Josh Papalii", "Daine Laurie", "Sebastian Kris", "Joe Roddy"],
    "CRO": ["William Kennedy", "Sione Katoa", "Sione Katoa 2", "Jesse Ramien", "Kayal Iro", "Ronaldo Mulitalo", "Braydon Trindall", "Nicholas Hynes", "Addin Fonua-Blake", "Addin Fonua Blake", "Blayke Brailey", "Thomas Hazelton", "Briton Nikora", "Teig Wilton", "Cameron McInnes", "Cameron Mcinnes", "Siosifa Talakai", "Billy Burns", "Oregon Kaufusi", "Jesse Colquhoun", "Mawene Hiroti", "Jayden Berrell"],
    "DOL": ["Hamiso Tabuai-Fidow", "Hamiso Tabuai Fidow", "Jamayne Isaako", "Jack Bostock", "Herbie Farnworth", "Selwyn Cobbo", "Kodi Nikorima", "Brad Schneider", "Thomas Flegler", "Jeremy Marshall-King", "Jeremy Marshall King", "Francis Molo", "Connelly Lemuelu", "Kulikefu Finefeuiaki", "Morgan Knowles", "Kurt Donoghoe", "Max Plath", "Tom Gilbert", "Felise Kaufusi", "Ray Stone", "Jake Averillo"],
    "GLD": ["Keano Kini", "Dean Ieremia", "Jojo Fifita", "Alexander Brimson", "Phillip Sami", "Jayden Campbell", "Zane Harrison", "Moeaki Fotuaika", "Oliver Pascoe", "Tino Fa'asuamaleaui", "Tino Faasuamaleaui", "Arama Hau", "Beau Fermor", "Chris Randall", "Kurtis Morrin", "Josh Patston", "Klese Haas", "Cooper Bai", "Sam Verrills", "Lachlan Ilias"],
    "MEL": ["Sualauvi Faalogo", "Siulagi Tuimalatu-Brown", "Siulagi Tuimalatu Brown", "Manaia Waitere", "Nick Meaney", "Moses Leo", "Tyran Wishart", "Jahrome Hughes", "Stefano Utoikamanu", "Trent Toelau", "Josh King", "Cooper Clarke", "Oryn Keeley", "Trent Loiero", "Hayden Watson", "Alec MacDonald", "Alec Macdonald", "Jack Hetherington", "Shawn Blore", "Joe Chan", "Angus Hinchey"],
    "NEW": ["Kalyn Ponga", "Dominic Young", "Dane Gagai", "Bradman Best", "Greg Marzhew", "Fletcher Sharpe", "Sandon Smith", "Cody Hopwood", "Phoenix Crossland", "Trey Mooney", "Jermaine McEwen", "Jermaine Mcewen", "Francis Manuleleua", "Mat Croker", "Harrison Graham", "Tyson Frizell", "Thomas Cant", "Brodie Jones", "Fletcher Hunt", "Lachlan Crouch"],
    "NQL": ["Scott Drinkwater", "Braidon Burns", "Zac Laybutt", "Tom Chester", "Murray Taulagi", "Jake Clifford", "Jaxon Purdue", "Thomas Mikaele", "Soni Luke", "Jason Taumalolo", "Heilum Luki", "Jeremiah Nanai", "Reuben Cotter", "Ethan King", "John Bateman", "Matthew Lodge", "Coen Hess", "Sam McIntyre", "Sam Mcintyre", "Kaiden Lahrs"],
    "NZW": ["Charnze Nicoll-Klokstad", "Charnze Nicoll Klokstad", "Dallin Watene-Zelezniak", "Dallin Watene Zelezniak", "Ali Leiataua", "Adam Pompey", "Alofiana Khan-Pereira", "Alofiana Khan Pereira", "Chanel Harris-Tavita", "Chanel Harris Tavita", "Te Maire Martin", "James Fisher-Harris", "James Fisher Harris", "Wayde Egan", "Mitchell Barnett", "Kurt Capewell", "Jacob Laban", "Erin Clark", "Samuel Healey", "Tanner Stowers-Smith", "Tanner Stowers Smith", "Demitric Vaimauga", "Leka Halasima", "Luke Metcalf", "Eddie Ieremia-Toeava", "Eddie Ieremia Toeava"],
    "PAR": ["Isaiah Iongi", "Brian Kelly", "Will Penisini", "Jordan Samrani", "Josh Addo-Carr", "Josh Addo Carr", "Ronald Volkman", "Mitchell Moses", "Sam Tuivaiti", "Tallyn Da Silva", "Jack Williams", "Kelma Tuilagi", "Kitione Kautoga", "Jack de Belin", "Jack De Belin", "Dylan Walker", "Junior Paulo", "Teancum Brown", "Harrison Edwards", "Joash Papalii", "Toni Mataele"],
    "PEN": ["Jaxen Edgar", "Thomas Jenkins", "Paul Alamoti", "Casey McLean", "Casey Mclean", "Brian To'o", "Brian Too", "Jack Cogger", "Nathan Cleary", "Moses Leota", "Freddy Lussick", "Lindsay Smith", "Isaiah Papali'i", "Isaiah Papalii", "Liam Martin", "Isaah Yeo", "Billy Scott", "Scott Sorensen", "Liam Henry", "Billy Phillips", "Izack Tago", "Jack Cole"],
    "SOU": ["Matt Dufty", "Alex Johnston", "Latrell Siegwalt", "Jack Wighton", "Campbell Graham", "Cody Walker", "Ashton Ward", "Tevita Tatola", "Brandon Smith", "John Radel", "Keaon Koloamatangi", "Euan Aitken", "Lachlan Hubner", "Jye Gray", "Jamie Humphreys", "Liam Le Blanc", "Sean Keppie", "Jayden Sullivan", "Edward Kosi"],
    "STI": ["Clinton Gutherson", "Setu Tu", "Mathew Feagai", "Valentine Holmes", "Tyrell Sloan", "Daniel Atkinson", "Kyle Flanagan", "Loko Pasifiki Tonga", "Damien Cook", "Toby Couchman", "Dylan Egan", "Hamish Stewart", "Ryan Couchman", "Jacob Liddle", "Luciano Leilua", "Josh Kerr", "Jacob Halangahu", "Moses Suli", "Lyhkan King-Togia", "Lyhkan King Togia"],
    "SYD": ["James Tedesco", "Tommy Talau", "Hugo Savala", "Robert Toia", "Mark Nawaqanitawase", "Daly Cherry-Evans", "Daly Cherry Evans", "Sam Walker", "Naufahu Whyte", "Reece Robson", "Spencer Leniu", "Nat Butcher", "Siua Wong", "Victor Radley", "Connor Watson", "Salesi Foketi", "Egan Butcher", "Taylor Losalu", "Cody Ramsey", "Reece Foley"],
    "WST": ["Jahream Bula", "Junior Tupou", "Heamasi Makasini", "Patrick Herbert", "Sunia Turuva", "Jarome Luai", "Adam Doueihi", "Terrell May", "Apisai Koroisau", "Fonua Pole", "Samuela Fainu", "Sione Fainu", "Alex Twal", "Heath Mason", "Charlie Murray", "Alex Seyfarth", "Tony Sukkar", "Tristan Hope", "Starford To'a", "Starford Toa"]
  }
};
