/* Auto-generated by cloud_fetch.py — DO NOT hand-edit (overwritten each run).
 * Josh's footytips comp snapshot: standings + each member's picks for the
 * round (picks appear as games lock / the round starts). Powers the
 * comp-aware tip policy; front-end live-refreshes between runs. */
window.NRL_COMP = {
 "round": 26,
 "finishRound": 31,
 "fetched": "2026-08-27T09:49:15+00:00",
 "members": [
  {
   "name": "Brigitte",
   "me": false,
   "aff": {
    "NEW": [
     12,
     23
    ],
    "NQL": [
     13,
     22
    ],
    "CAN": [
     14,
     21
    ],
    "STI": [
     3,
     22
    ],
    "MEL": [
     9,
     22
    ],
    "PAR": [
     3,
     20
    ],
    "NZW": [
     21,
     22
    ],
    "SYD": [
     22,
     22
    ],
    "BRI": [
     5,
     21
    ],
    "PEN": [
     16,
     20
    ],
    "CRO": [
     12,
     22
    ],
    "GLD": [
     1,
     22
    ],
    "MAN": [
     14,
     22
    ],
    "CBR": [
     10,
     23
    ],
    "DOL": [
     15,
     22
    ],
    "SOU": [
     9,
     22
    ],
    "WST": [
     6,
     22
    ]
   },
   "rank": 1,
   "mv": "",
   "roundScore": 0,
   "totalScore": 122,
   "totalMargin": 422,
   "picks": {}
  },
  {
   "name": "Claire with an i",
   "me": false,
   "aff": {
    "NEW": [
     11,
     23
    ],
    "NQL": [
     16,
     22
    ],
    "CAN": [
     9,
     22
    ],
    "STI": [
     7,
     22
    ],
    "MEL": [
     6,
     22
    ],
    "PAR": [
     3,
     22
    ],
    "NZW": [
     16,
     22
    ],
    "SYD": [
     11,
     22
    ],
    "BRI": [
     5,
     22
    ],
    "PEN": [
     21,
     22
    ],
    "CRO": [
     12,
     22
    ],
    "GLD": [
     2,
     22
    ],
    "MAN": [
     20,
     22
    ],
    "CBR": [
     13,
     23
    ],
    "DOL": [
     16,
     22
    ],
    "SOU": [
     11,
     22
    ],
    "WST": [
     9,
     22
    ]
   },
   "rank": 2,
   "mv": "",
   "roundScore": 0,
   "totalScore": 121,
   "totalMargin": 440,
   "picks": {}
  },
  {
   "name": "Thorners69",
   "me": false,
   "aff": {
    "NEW": [
     10,
     23
    ],
    "NQL": [
     7,
     21
    ],
    "CAN": [
     9,
     22
    ],
    "STI": [
     5,
     22
    ],
    "MEL": [
     12,
     21
    ],
    "PAR": [
     5,
     22
    ],
    "NZW": [
     14,
     22
    ],
    "SYD": [
     21,
     22
    ],
    "BRI": [
     9,
     22
    ],
    "PEN": [
     17,
     21
    ],
    "CRO": [
     16,
     22
    ],
    "GLD": [
     6,
     21
    ],
    "MAN": [
     10,
     21
    ],
    "CBR": [
     15,
     23
    ],
    "DOL": [
     12,
     21
    ],
    "SOU": [
     9,
     22
    ],
    "WST": [
     8,
     22
    ]
   },
   "rank": 3,
   "mv": "",
   "roundScore": 0,
   "totalScore": 120,
   "totalMargin": 457,
   "picks": {}
  },
  {
   "name": "Jake",
   "me": false,
   "aff": {
    "MEL": [
     12,
     22
    ],
    "PAR": [
     3,
     22
    ],
    "NZW": [
     16,
     22
    ],
    "SYD": [
     17,
     22
    ],
    "BRI": [
     8,
     22
    ],
    "PEN": [
     22,
     22
    ],
    "CRO": [
     13,
     22
    ],
    "GLD": [
     2,
     22
    ],
    "MAN": [
     11,
     21
    ],
    "CBR": [
     11,
     22
    ],
    "DOL": [
     14,
     20
    ],
    "SOU": [
     12,
     21
    ],
    "WST": [
     12,
     21
    ],
    "NQL": [
     9,
     21
    ],
    "STI": [
     2,
     20
    ],
    "NEW": [
     10,
     21
    ],
    "CAN": [
     8,
     21
    ]
   },
   "rank": 4,
   "mv": "",
   "roundScore": 0,
   "totalScore": 118,
   "totalMargin": 436,
   "picks": {}
  },
  {
   "name": "Special unit",
   "me": true,
   "aff": {
    "NEW": [
     11,
     23
    ],
    "NQL": [
     12,
     22
    ],
    "CAN": [
     13,
     21
    ],
    "STI": [
     2,
     22
    ],
    "MEL": [
     14,
     22
    ],
    "PAR": [
     4,
     21
    ],
    "NZW": [
     15,
     22
    ],
    "SYD": [
     22,
     22
    ],
    "BRI": [
     8,
     21
    ],
    "PEN": [
     16,
     19
    ],
    "CRO": [
     13,
     21
    ],
    "GLD": [
     2,
     22
    ],
    "MAN": [
     12,
     21
    ],
    "CBR": [
     8,
     23
    ],
    "DOL": [
     10,
     20
    ],
    "SOU": [
     13,
     20
    ],
    "WST": [
     7,
     22
    ]
   },
   "rank": 5,
   "mv": "",
   "roundScore": 0,
   "totalScore": 109,
   "totalMargin": 455,
   "picks": {}
  },
  {
   "name": "Susie loo",
   "me": false,
   "aff": {
    "NEW": [
     16,
     23
    ],
    "NQL": [
     11,
     22
    ],
    "CAN": [
     19,
     22
    ],
    "STI": [
     5,
     22
    ],
    "MEL": [
     7,
     22
    ],
    "PAR": [
     1,
     22
    ],
    "NZW": [
     12,
     22
    ],
    "SYD": [
     8,
     22
    ],
    "BRI": [
     5,
     22
    ],
    "PEN": [
     21,
     22
    ],
    "CRO": [
     9,
     22
    ],
    "GLD": [
     3,
     22
    ],
    "MAN": [
     22,
     22
    ],
    "CBR": [
     14,
     23
    ],
    "DOL": [
     13,
     22
    ],
    "SOU": [
     13,
     22
    ],
    "WST": [
     9,
     22
    ]
   },
   "rank": 6,
   "mv": "",
   "roundScore": 0,
   "totalScore": 103,
   "totalMargin": 487,
   "picks": {}
  }
 ]
};
