/* rebuilt by cloud_fetch.py from the live Zero Tackle team lists.
   The named squad per club for the round below. The front-end uses this to
   cancel an injury-table entry for a player who is actually named in the
   side — without it, a season-long 'TBC' keeps a fit player half-out
   forever. Empty/stale is safe: the model just falls back to the
   injury table alone. */
window.NRL_LINEUPS = {
  "round": 24,
  "teams": {
    "BRI": ["Reece Walsh", "Josiah Karapani", "Kotoni Staggs", "Deine Mariner", "Grant Anderson", "Ezra Mam", "Tom Duffy", "Xavier Willison", "Billy Walters", "Payne Haas", "Jaiyden Hunt", "Jordan Riki", "Patrick Carrigan", "Aublix Tawha", "Jack Gosiewski", "Blake Mozer", "Gehamat Shibasaki", "Ben Hunt", "Va'a Semu", "Vaa Semu"],
    "CAN": ["Connor Tracey", "Jacob Kiraz", "Matt Burton", "Enari Tuala", "Jethro Rinakama", "Stephen Crichton", "Lachlan Galvin", "Max King", "Bailey Hayward", "Leo Thompson", "Viliame Kikau", "Jacob Preston", "Jaeman Salmon", "Kurt Mann", "Josh Curran", "Harry Hayes", "Bronson Xerri", "Alekolasimi Jones", "Jake Turpin"],
    "CBR": ["Kaeo Weekes", "Jed Stuart", "Savelio Tamale", "Matthew Timoko", "Xavier Savage", "Ethan Strange", "Ethan Sanders", "Ata Mariota", "Owen Pattie", "Joseph Tapine", "Zac Hosking", "Matty Nicholson", "Morgan Smithies", "Tom Starling", "Joe Roddy", "Josh Papalii", "Daine Laurie", "Vena Patuki-Case", "Vena Patuki Case", "Sebastian Kris"],
    "CRO": ["William Kennedy", "Sione Katoa", "Sione Katoa 2", "Mawene Hiroti", "Kayal Iro", "Ronaldo Mulitalo", "Braydon Trindall", "Nicholas Hynes", "Oregon Kaufusi", "Blayke Brailey", "Jesse Colquhoun", "Briton Nikora", "Teig Wilton", "Cameron McInnes", "Cameron Mcinnes", "Hohepa Puru", "Billy Burns", "Siosifa Talakai", "Thomas Hazelton", "Braden Hamlin Uele", "Samuel Stonestreet"],
    "DOL": ["Hamiso Tabuai-Fidow", "Hamiso Tabuai Fidow", "Jamayne Isaako", "Jack Bostock", "Herbie Farnworth", "Selwyn Cobbo", "Kodi Nikorima", "Isaiya Katoa", "Thomas Flegler", "Jeremy Marshall-King", "Jeremy Marshall King", "Tom Gilbert", "Connelly Lemuelu", "Kulikefu Finefeuiaki", "Morgan Knowles", "Francis Molo", "Max Plath", "Ray Stone", "Felise Kaufusi", "Brad Schneider", "Tevita Naufahu"],
    "GLD": ["Keano Kini", "Phillip Sami", "Jojo Fifita", "Alexander Brimson", "Jaylan De Groot", "Jayden Campbell", "Lachlan Ilias", "Moeaki Fotuaika", "Oliver Pascoe", "Tino Fa'asuamaleaui", "Tino Faasuamaleaui", "Josh Patston", "Beau Fermor", "Chris Randall", "Kurtis Morrin", "Klese Haas", "Cooper Bai", "Bodhi Sharpley", "Sam Verrills", "Siale Faeamani"],
    "MAN": ["Clayton Faulalo", "Jason Saab", "Tolutau Koula", "Reuben Garrick", "Lehi Hopoate", "Joey Walsh", "Jamal Fogarty", "Simione Laiafi", "Brandon Wakeham", "Fletcher Baker", "Haumole Olakau'atu", "Haumole Olakauatu", "Corey Waddell", "Jake Trbojevic", "Nathan Brown", "Jake Simpkin", "Nicholas Lenaz", "Jackson Shereb", "Josh Feledy", "Hugo Hart"],
    "NEW": ["Kalyn Ponga", "Dominic Young", "Dane Gagai", "Fletcher Hunt", "Greg Marzhew", "Fletcher Sharpe", "Sandon Smith", "Cody Hopwood", "Phoenix Crossland", "Trey Mooney", "Jermaine McEwen", "Jermaine Mcewen", "Francis Manuleleua", "Mat Croker", "Harrison Graham", "Tyson Frizell", "Lachlan Crouch", "Thomas Cant", "Pasami Saulo", "Toby Winter"],
    "NQL": ["Scott Drinkwater", "Braidon Burns", "Zac Laybutt", "Tom Chester", "Murray Taulagi", "Jake Clifford", "Jaxon Purdue", "Griffin Neame", "Reed Mahoney", "Jason Taumalolo", "Heilum Luki", "Kai O'Donnell", "Kai Odonnell", "Reuben Cotter", "Soni Luke", "Thomas Mikaele", "John Bateman", "Coen Hess", "Sam McIntyre", "Sam Mcintyre", "Ethan King"],
    "NZW": ["Charnze Nicoll-Klokstad", "Charnze Nicoll Klokstad", "Dallin Watene-Zelezniak", "Dallin Watene Zelezniak", "Ali Leiataua", "Leka Halasima", "Alofiana Khan-Pereira", "Alofiana Khan Pereira", "Chanel Harris-Tavita", "Chanel Harris Tavita", "Luke Metcalf", "James Fisher-Harris", "James Fisher Harris", "Wayde Egan", "Mitchell Barnett", "Kurt Capewell", "Jacob Laban", "Erin Clark", "Samuel Healey", "Tanner Stowers-Smith", "Tanner Stowers Smith", "Eddie Ieremia-Toeava", "Eddie Ieremia Toeava", "Taine Tuaupiki", "Demitric Vaimauga", "Adam Pompey"],
    "PAR": ["Te Hurinui Twidle", "Brian Kelly", "Will Penisini", "Jordan Samrani", "Josh Addo-Carr", "Josh Addo Carr", "Ronald Volkman", "Mitchell Moses", "Luca Moretti", "Tallyn Da Silva", "Junior Paulo", "Jack Williams", "Kitione Kautoga", "Saxon Pryke", "Dylan Walker", "Teancum Brown", "Sean Russell", "Harrison Edwards", "Jezaiah Funa-Iuta", "Jezaiah Funa Iuta", "Toni Mataele"],
    "PEN": ["Dylan Edwards", "Thomas Jenkins", "Paul Alamoti", "Izack Tago", "Brian To'o", "Brian Too", "Jack Cogger", "Nathan Cleary", "Moses Leota", "Freddy Lussick", "Liam Henry", "Isaiah Papali'i", "Isaiah Papalii", "Liam Martin", "Lindsay Smith", "Scott Sorensen", "Luron Patea", "Billy Phillips", "Blaize Talagi", "Jaxen Edgar", "Billy Scott"],
    "SOU": ["Matt Dufty", "Alex Johnston", "Tallis Duncan", "Jack Wighton", "Campbell Graham", "Cody Walker", "Jayden Sullivan", "Tevita Tatola", "Brandon Smith", "Keaon Koloamatangi", "David Fifita", "Adam Elliott", "Cameron Murray", "Lachlan Hubner", "Sean Keppie", "Euan Aitken", "Peter Mamouzelos", "Jye Gray", "Edward Kosi"],
    "STI": ["Mathew Feagai", "Setu Tu", "Moses Suli", "Valentine Holmes", "Tyrell Sloan", "Lyhkan King-Togia", "Lyhkan King Togia", "Kyle Flanagan", "Loko Pasifiki Tonga", "Damien Cook", "Emre Guler", "Dylan Egan", "Hamish Stewart", "Ryan Couchman", "Jacob Liddle", "Toby Couchman", "Jacob Halangahu", "Jacob Webster", "Daniel Atkinson", "Blake Lawrie"],
    "SYD": ["Cody Ramsey", "Billy Smith", "Hugo Savala", "Robert Toia", "Mark Nawaqanitawase", "Daly Cherry-Evans", "Daly Cherry Evans", "Sam Walker", "Naufahu Whyte", "Reece Robson", "Spencer Leniu", "Salesi Foketi", "Siua Wong", "Victor Radley", "Connor Watson", "Lindsay Collins", "Nat Butcher", "Egan Butcher", "Tommy Talau", "Rex Bassingthwaighte"],
    "WST": ["Jahream Bula", "Junior Tupou", "Solomone Saukuru", "Patrick Herbert", "Sunia Turuva", "Jarome Luai", "Adam Doueihi", "Terrell May", "Apisai Koroisau", "Fonua Pole", "Samuela Fainu", "Tony Sukkar", "Alex Twal", "Heath Mason", "Sione Fainu", "Alex Seyfarth", "Bunty Afoa", "Tristan Hope", "Tino Tavana"]
  }
};
