/* rebuilt by cloud_fetch.py from the live Zero Tackle team lists.
   The named squad per club for the round below. The front-end uses this to
   cancel an injury-table entry for a player who is actually named in the
   side — without it, a season-long 'TBC' keeps a fit player half-out
   forever. Empty/stale is safe: the model just falls back to the
   injury table alone. */
window.NRL_LINEUPS = {
  "round": 23,
  "teams": {
    "BRI": ["Reece Walsh", "Josiah Karapani", "Kotoni Staggs", "Deine Mariner", "Grant Anderson", "Ezra Mam", "Tom Duffy", "Xavier Willison", "Billy Walters", "Payne Haas", "Jaiyden Hunt", "Jordan Riki", "Patrick Carrigan", "Ben Hunt", "Va'a Semu", "Vaa Semu", "Ben Talty", "Gehamat Shibasaki", "Jack Gosiewski", "Hayze Perham"],
    "CAN": ["Connor Tracey", "Jacob Kiraz", "Matt Burton", "Enari Tuala", "Jethro Rinakama", "Stephen Crichton", "Lachlan Galvin", "Max King", "Bailey Hayward", "Leo Thompson", "Viliame Kikau", "Jacob Preston", "Jaeman Salmon", "Kurt Mann", "Josh Curran", "Harry Hayes", "Sitili Tupouniua", "Bronson Xerri", "Jake Turpin"],
    "CBR": ["Kaeo Weekes", "Jed Stuart", "Simi Sasagi", "Matthew Timoko", "Xavier Savage", "Ethan Strange", "Ethan Sanders", "Corey Horsburgh", "Owen Pattie", "Joseph Tapine", "Zac Hosking", "Ata Mariota", "Morgan Smithies", "Tom Starling", "Joe Roddy", "Josh Papalii", "Daine Laurie", "Savelio Tamale", "Matty Nicholson"],
    "CRO": ["William Kennedy", "Sione Katoa", "Sione Katoa 2", "Jesse Ramien", "Mawene Hiroti", "Ronaldo Mulitalo", "Braydon Trindall", "Nicholas Hynes", "Addin Fonua-Blake", "Addin Fonua Blake", "Blayke Brailey", "Jesse Colquhoun", "Briton Nikora", "Teig Wilton", "Cameron McInnes", "Cameron Mcinnes", "Hohepa Puru", "Billy Burns", "Oregon Kaufusi", "Thomas Hazelton", "Michael Gabrael", "Braden Hamlin Uele"],
    "DOL": ["Hamiso Tabuai-Fidow", "Hamiso Tabuai Fidow", "Jamayne Isaako", "Jack Bostock", "Herbie Farnworth", "Selwyn Cobbo", "Kodi Nikorima", "Isaiya Katoa", "Thomas Flegler", "Jeremy Marshall-King", "Jeremy Marshall King", "Francis Molo", "Connelly Lemuelu", "Kulikefu Finefeuiaki", "Morgan Knowles", "Kurt Donoghoe", "Max Plath", "Tom Gilbert", "Felise Kaufusi", "Brad Schneider", "Brian Pouniu"],
    "GLD": ["Keano Kini", "Dean Ieremia", "Jojo Fifita", "Jaylan De Groot", "Phillip Sami", "Jayden Campbell", "Alexander Brimson", "Moeaki Fotuaika", "Sam Verrills", "Tino Fa'asuamaleaui", "Tino Faasuamaleaui", "Beau Fermor", "Josh Patston", "Chris Randall", "Oliver Pascoe", "Kurtis Morrin", "Klese Haas", "Cooper Bai", "Lachlan Ilias", "Arama Hau"],
    "MAN": ["Lehi Hopoate", "Jason Saab", "Tolutau Koula", "Reuben Garrick", "Blake Wilson", "Joey Walsh", "Jamal Fogarty", "Taniela Paseka", "Brandon Wakeham", "Simione Laiafi", "Haumole Olakau'atu", "Haumole Olakauatu", "Corey Waddell", "Jake Trbojevic", "Jake Simpkin", "Nathan Brown", "Fletcher Baker", "Jackson Shereb", "Josh Feledy", "Nicholas Lenaz"],
    "MEL": ["Sualauvi Faalogo", "Siulagi Tuimalatu-Brown", "Siulagi Tuimalatu Brown", "Nick Meaney", "Joe Chan", "Moses Leo", "Cameron Munster", "Hayden Watson", "Stefano Utoikamanu", "Tyran Wishart", "Josh King", "Cooper Clarke", "Oryn Keeley", "Trent Loiero", "Trent Toelau", "Shawn Blore", "Davvy Moale", "Angus Hinchey", "Jack Hetherington", "Manaia Waitere"],
    "NEW": ["Kalyn Ponga", "Dominic Young", "Dane Gagai", "Bradman Best", "Greg Marzhew", "Fletcher Sharpe", "Sandon Smith", "Tyson Frizell", "Phoenix Crossland", "Trey Mooney", "Jermaine McEwen", "Jermaine Mcewen", "Francis Manuleleua", "Mat Croker", "Harrison Graham", "Cody Hopwood", "Lachlan Crouch", "Thomas Cant", "Fletcher Hunt", "Brodie Jones"],
    "NQL": ["Scott Drinkwater", "Braidon Burns", "Zac Laybutt", "Tom Chester", "Murray Taulagi", "Jake Clifford", "Jaxon Purdue", "Griffin Neame", "Soni Luke", "Jason Taumalolo", "Heilum Luki", "Kai O'Donnell", "Kai Odonnell", "Reuben Cotter", "Ethan King", "Thomas Mikaele", "Coen Hess", "John Bateman", "Matthew Lodge", "Sam McIntyre", "Sam Mcintyre"],
    "NZW": ["Charnze Nicoll-Klokstad", "Charnze Nicoll Klokstad", "Dallin Watene-Zelezniak", "Dallin Watene Zelezniak", "Ali Leiataua", "Leka Halasima", "Alofiana Khan-Pereira", "Alofiana Khan Pereira", "Chanel Harris-Tavita", "Chanel Harris Tavita", "Luke Metcalf", "James Fisher-Harris", "James Fisher Harris", "Wayde Egan", "Mitchell Barnett", "Kurt Capewell", "Jacob Laban", "Erin Clark", "Samuel Healey", "Tanner Stowers-Smith", "Tanner Stowers Smith", "Morgan Gannon", "Eddie Ieremia-Toeava", "Eddie Ieremia Toeava", "Taine Tuaupiki", "Adam Pompey"],
    "PAR": ["Isaiah Iongi", "Brian Kelly", "Will Penisini", "Jordan Samrani", "Josh Addo-Carr", "Josh Addo Carr", "Ronald Volkman", "Mitchell Moses", "Sam Tuivaiti", "Tallyn Da Silva", "Luca Moretti", "Jack Williams", "Kitione Kautoga", "Jack de Belin", "Jack De Belin", "Saxon Pryke", "Junior Paulo", "Teancum Brown", "Joash Papalii", "Jezaiah Funa-Iuta", "Jezaiah Funa Iuta", "Toni Mataele"],
    "PEN": ["Jaxen Edgar", "Thomas Jenkins", "Paul Alamoti", "Izack Tago", "Brian To'o", "Brian Too", "Jack Cole", "Nathan Cleary", "Moses Leota", "Freddy Lussick", "Lindsay Smith", "Isaiah Papali'i", "Isaiah Papalii", "Liam Martin", "Isaah Yeo", "Billy Scott", "Scott Sorensen", "Liam Henry", "Billy Phillips", "Blaize Talagi", "Luron Patea"],
    "SOU": ["Matt Dufty", "Alex Johnston", "Tallis Duncan", "Jack Wighton", "Jye Gray", "Cody Walker", "Ashton Ward", "Tevita Tatola", "Brandon Smith", "Keaon Koloamatangi", "David Fifita", "Adam Elliott", "Cameron Murray", "Lachlan Hubner", "Sean Keppie", "Jamie Humphreys", "Jayden Sullivan", "Thomas Fletcher", "Liam Le Blanc"],
    "STI": ["Clinton Gutherson", "Setu Tu", "Moses Suli", "Valentine Holmes", "Tyrell Sloan", "Lyhkan King-Togia", "Lyhkan King Togia", "Kyle Flanagan", "Loko Pasifiki Tonga", "Damien Cook", "Emre Guler", "Dylan Egan", "Hamish Stewart", "Ryan Couchman", "Jacob Liddle", "Josh Kerr", "Jacob Halangahu", "Jacob Webster", "Daniel Atkinson", "Mathew Feagai"],
    "SYD": ["Cody Ramsey", "Billy Smith", "Hugo Savala", "Robert Toia", "Mark Nawaqanitawase", "Daly Cherry-Evans", "Daly Cherry Evans", "Sam Walker", "Naufahu Whyte", "Reece Robson", "Nat Butcher", "Salesi Foketi", "Siua Wong", "Victor Radley", "Spencer Leniu", "Connor Watson", "Lindsay Collins", "Egan Butcher", "Tommy Talau", "Rex Bassingthwaighte"]
  }
};
