// Auto-generated by parse_nrl.py — DO NOT hand-edit (edits will be overwritten next run).
// To regenerate: python3 parse_nrl.py --ladder ladder_dump.html --draw draw_dump.html --out nrl_data.js --season 2026 --source zerotackle.com [--odds odds_dump.txt] [--injuries injuries_dump.txt]
// (see sources.md for where to fetch fresh dumps).
// Data current to end of Finals Week 3, 2026.
// Schema v3: teams add colour/home/away/news; fixtures add city/odds/h2h.
// fixture.odds carries {open,close} decimal-odds snapshots for CLV
// (closing-line-value); `open` is carried forward run-to-run within a round.
// The legacy flat {home,away} shape and null are still accepted everywhere.
// fixture.weather is retired (2026-08-04) — kept as null for one deploy
// cycle for CDN-cached old pages, then the key can be dropped.
// Time-sensitive fields (odds, news) stay null unless the optional
// --odds/--injuries dumps are supplied that week.
window.NRL_DATA = {
  "updated": "2026-10-06",
  "season": 2026,
  "round": 31,
  "roundName": "Grand Final",
  "finals": true,
  "source": "zerotackle.com",
  "teams": [
    {
      "name": "Panthers",
      "short": "PEN",
      "colour": "#0a0a0a",
      "P": 24,
      "W": 18,
      "L": 6,
      "PF": 683,
      "PA": 347,
      "last5": 4,
      "home": {
        "P": 14,
        "W": 11,
        "L": 3,
        "PF": 381,
        "PA": 188
      },
      "away": {
        "P": 12,
        "W": 8,
        "L": 4,
        "PF": 335,
        "PA": 193
      },
      "news": "Blaize Talagi (Achilles); Nathan Cleary (Leg); Jack Cogger (Suspension) — back Finals Week 3"
    },
    {
      "name": "Warriors",
      "short": "NZW",
      "colour": "#231f20",
      "P": 24,
      "W": 18,
      "L": 6,
      "PF": 728,
      "PA": 418,
      "last5": 3,
      "home": {
        "P": 14,
        "W": 10,
        "L": 4,
        "PF": 383,
        "PA": 260
      },
      "away": {
        "P": 12,
        "W": 8,
        "L": 4,
        "PF": 371,
        "PA": 196
      },
      "news": "Tanah Boyd (ACL) — back Next Season; Jackson Ford (Ankle) — back Next Season"
    },
    {
      "name": "Dolphins",
      "short": "DOL",
      "colour": "#ee3524",
      "P": 24,
      "W": 17,
      "L": 7,
      "PF": 662,
      "PA": 506,
      "last5": 4,
      "home": {
        "P": 13,
        "W": 8,
        "L": 5,
        "PF": 364,
        "PA": 351
      },
      "away": {
        "P": 13,
        "W": 10,
        "L": 3,
        "PF": 344,
        "PA": 207
      },
      "news": null
    },
    {
      "name": "Roosters",
      "short": "SYD",
      "colour": "#e2231a",
      "P": 24,
      "W": 16,
      "L": 8,
      "PF": 619,
      "PA": 501,
      "last5": 3,
      "home": {
        "P": 14,
        "W": 10,
        "L": 4,
        "PF": 336,
        "PA": 259
      },
      "away": {
        "P": 14,
        "W": 9,
        "L": 5,
        "PF": 396,
        "PA": 309
      },
      "news": "Blake Steep (ACL) — back Next Season; Connor Watson (Concussion) — back Next Season"
    },
    {
      "name": "Sharks",
      "short": "CRO",
      "colour": "#00a9e0",
      "P": 24,
      "W": 14,
      "L": 10,
      "PF": 672,
      "PA": 523,
      "last5": 2,
      "home": {
        "P": 13,
        "W": 9,
        "L": 4,
        "PF": 388,
        "PA": 262
      },
      "away": {
        "P": 13,
        "W": 6,
        "L": 7,
        "PF": 320,
        "PA": 323
      },
      "news": "Mawene Hiroti (Knee) — back Next Season; Nicho Hynes (Concussion) — back Next Season; Jesse Ramien (Pectoral) — back Next Season; Toby Rudolf (Knee) — back Pre-Season Challenge; Braydon Trindall (Shoulder) — back Pre-Season Challenge"
    },
    {
      "name": "Rabbitohs",
      "short": "SOU",
      "colour": "#00954c",
      "P": 24,
      "W": 14,
      "L": 10,
      "PF": 694,
      "PA": 581,
      "last5": 3,
      "home": {
        "P": 13,
        "W": 9,
        "L": 4,
        "PF": 378,
        "PA": 297
      },
      "away": {
        "P": 12,
        "W": 5,
        "L": 7,
        "PF": 326,
        "PA": 304
      },
      "news": "Ashton Ward (Hamstring) — back Next Season; Cody Walker (Calf) — back Next Season; Euan Aitken (Shoulder) — back Next Season"
    },
    {
      "name": "Knights",
      "short": "NEW",
      "colour": "#00539b",
      "P": 24,
      "W": 14,
      "L": 10,
      "PF": 633,
      "PA": 591,
      "last5": 3,
      "home": {
        "P": 12,
        "W": 8,
        "L": 4,
        "PF": 283,
        "PA": 303
      },
      "away": {
        "P": 16,
        "W": 9,
        "L": 7,
        "PF": 422,
        "PA": 341
      },
      "news": "Dylan Brown (ACL) — back Next Season; Trey Mooney (Shoulder) — back Next Season; Jacob Saifiti (Suspension) — back Next Season; Phoenix Crossland (Suspension) — back World Cup"
    },
    {
      "name": "Cowboys",
      "short": "NQL",
      "colour": "#002b5c",
      "P": 24,
      "W": 13,
      "L": 11,
      "PF": 568,
      "PA": 652,
      "last5": 2,
      "home": {
        "P": 12,
        "W": 7,
        "L": 5,
        "PF": 294,
        "PA": 367
      },
      "away": {
        "P": 13,
        "W": 6,
        "L": 7,
        "PF": 290,
        "PA": 311
      },
      "news": "Thomas Mikaele (Hamstring) — back World Cup"
    },
    {
      "name": "Sea Eagles",
      "short": "MAN",
      "colour": "#6f1a3c",
      "P": 24,
      "W": 11,
      "L": 13,
      "PF": 623,
      "PA": 524,
      "last5": 2,
      "home": {
        "P": 12,
        "W": 6,
        "L": 6,
        "PF": 269,
        "PA": 247
      },
      "away": {
        "P": 12,
        "W": 5,
        "L": 7,
        "PF": 354,
        "PA": 277
      },
      "news": "Luke Brooks (ACL) — back Next Season; Kobe Hetherington (Biceps) — back Next Season; Joey Walsh (Jaw) — back Next Season; Tolutau Koula (Ankle) — back World Cup"
    },
    {
      "name": "Storm",
      "short": "MEL",
      "colour": "#4b2e83",
      "P": 24,
      "W": 11,
      "L": 13,
      "PF": 594,
      "PA": 576,
      "last5": 3,
      "home": {
        "P": 12,
        "W": 7,
        "L": 5,
        "PF": 322,
        "PA": 274
      },
      "away": {
        "P": 12,
        "W": 4,
        "L": 8,
        "PF": 272,
        "PA": 302
      },
      "news": "Will Warbrick (Achilles) — back Next Season; Xavier Coates (Achilles) — back Next Season; Jack Howarth (Shoulder) — back Next Season; Jahrome Hughes (Hamstring) — back World Cup"
    },
    {
      "name": "Raiders",
      "short": "CBR",
      "colour": "#8bc53f",
      "P": 24,
      "W": 11,
      "L": 13,
      "PF": 581,
      "PA": 626,
      "last5": 2,
      "home": {
        "P": 12,
        "W": 5,
        "L": 7,
        "PF": 292,
        "PA": 282
      },
      "away": {
        "P": 12,
        "W": 6,
        "L": 6,
        "PF": 289,
        "PA": 344
      },
      "news": "Hudson Young (Achilles) — back Next Season; Zac Hosking (Hamstring) — back Next Season; Savelio Tamale (Knee) — back Next Season; Corey Horsburgh (Shoulder) — back Next Season"
    },
    {
      "name": "Bulldogs",
      "short": "CAN",
      "colour": "#00337f",
      "P": 24,
      "W": 11,
      "L": 13,
      "PF": 476,
      "PA": 536,
      "last5": 1,
      "home": {
        "P": 12,
        "W": 7,
        "L": 5,
        "PF": 224,
        "PA": 228
      },
      "away": {
        "P": 12,
        "W": 4,
        "L": 8,
        "PF": 252,
        "PA": 308
      },
      "news": "Kurt Mann (Groin) — back Next Season; Sitili Tupouniua (Hamstring) — back World Cup"
    },
    {
      "name": "Eels",
      "short": "PAR",
      "colour": "#006eb5",
      "P": 24,
      "W": 9,
      "L": 15,
      "PF": 497,
      "PA": 678,
      "last5": 2,
      "home": {
        "P": 12,
        "W": 6,
        "L": 6,
        "PF": 258,
        "PA": 314
      },
      "away": {
        "P": 12,
        "W": 3,
        "L": 9,
        "PF": 239,
        "PA": 364
      },
      "news": "Matt Doorey (Knee) — back Next Season; J'maine Hopgood (ACL) — back Next Season; Isaiah Iongi (Knee) — back World Cup"
    },
    {
      "name": "Broncos",
      "short": "BRI",
      "colour": "#6c1d45",
      "P": 24,
      "W": 8,
      "L": 16,
      "PF": 471,
      "PA": 677,
      "last5": 2,
      "home": {
        "P": 12,
        "W": 2,
        "L": 10,
        "PF": 236,
        "PA": 351
      },
      "away": {
        "P": 12,
        "W": 6,
        "L": 6,
        "PF": 235,
        "PA": 326
      },
      "news": "Cory Paix (Shoulder) — back Next Season; Blake Mozer (Head knock) — back Next Season; Brendan Piakura (Concussion) — back Next Season; Preston Riki (Ankle) — back Next Season; Reece Walsh (Ankle) — back World Cup"
    },
    {
      "name": "Wests Tigers",
      "short": "WST",
      "colour": "#f68b1f",
      "P": 24,
      "W": 8,
      "L": 16,
      "PF": 445,
      "PA": 699,
      "last5": 1,
      "home": {
        "P": 12,
        "W": 5,
        "L": 7,
        "PF": 278,
        "PA": 339
      },
      "away": {
        "P": 12,
        "W": 3,
        "L": 9,
        "PF": 167,
        "PA": 360
      },
      "news": "Adam Doueihi (Shoulder) — back Next Season; Royce Hunt (Pectoral) — back Next Season; Taylan May (Shoulder) — back Next Season; Tony Sukkar (Concussion) — back Next Season; Kai Pearce-Paul (Pectoral) — back World Cup"
    },
    {
      "name": "Titans",
      "short": "GLD",
      "colour": "#fbb040",
      "P": 24,
      "W": 6,
      "L": 18,
      "PF": 477,
      "PA": 663,
      "last5": 0,
      "home": {
        "P": 12,
        "W": 3,
        "L": 9,
        "PF": 205,
        "PA": 352
      },
      "away": {
        "P": 12,
        "W": 3,
        "L": 9,
        "PF": 272,
        "PA": 311
      },
      "news": "Jaylan De Groot (Knee) — back Next Season; Jojo Fifita (Hip) — back Next Season; Brock Gray (ACL) — back Next Season; Zane Harrison (Hamstring) — back Next Season; Jaimin Jolliffe (Knee) — back Next Season; Oliver Pascoe (Concussion) — back Next Season"
    },
    {
      "name": "Dragons",
      "short": "STI",
      "colour": "#e2231a",
      "P": 24,
      "W": 5,
      "L": 19,
      "PF": 392,
      "PA": 717,
      "last5": 3,
      "home": {
        "P": 12,
        "W": 3,
        "L": 9,
        "PF": 202,
        "PA": 400
      },
      "away": {
        "P": 12,
        "W": 2,
        "L": 10,
        "PF": 190,
        "PA": 317
      },
      "news": "Hayden Buchanan (Shoulder) — back Next Season; Clinton Gutherson (Knee) — back Next Season; Hame Sele (Achilles) — back Next Season; Valentine Holmes (Ankle) — back World Cup; Jaydn Su'A (Pectoral) — back World Cup"
    }
  ],
  "fixtures": [
    {
      "home": "SYD",
      "away": "NEW",
      "venue": "Accor Stadium",
      "city": "Sydney",
      "kickoff": "2026-10-04T19:30:00+11:00",
      "odds": {
        "open": {
          "home": 1.44,
          "away": 2.8
        },
        "close": {
          "home": 1.7,
          "away": 2.13
        }
      },
      "weather": null,
      "h2h": null,
      "tz": "Australia/Sydney"
    }
  ],
  "byeTeams": [],
  "generatedAt": "2026-10-06T11:57:59+11:00",
  "changes": [],
  "changesSince": "2026-10-06T04:09:23+11:00"
};
