/* rebuilt by cloud_fetch.py from the live Zero Tackle team lists.
   The named squad per club for the round below. The front-end uses this to
   cancel an injury-table entry for a player who is actually named in the
   side — without it, a season-long 'TBC' keeps a fit player half-out
   forever. Empty/stale is safe: the model just falls back to the
   injury table alone. */
window.NRL_LINEUPS = {
  "round": 25,
  "teams": {
    "BRI": ["Hayze Perham", "Josiah Karapani", "Kotoni Staggs", "Deine Mariner", "Grant Anderson", "Ezra Mam", "Ben Hunt", "Xavier Willison", "Billy Walters", "Payne Haas", "Jaiyden Hunt", "Jordan Riki", "Patrick Carrigan", "Blake Mozer", "Jack Gosiewski", "Va'a Semu", "Vaa Semu", "Aublix Tawha", "Tom Duffy", "Gehamat Shibasaki"],
    "CAN": ["Connor Tracey", "Jacob Kiraz", "Matt Burton", "Bronson Xerri", "Enari Tuala", "Stephen Crichton", "Lachlan Galvin", "Max King", "Bailey Hayward", "Leo Thompson", "Viliame Kikau", "Jacob Preston", "Jaeman Salmon", "Kurt Mann", "Josh Curran", "Harry Hayes", "Alekolasimi Jones", "Jake Turpin", "Sean O'Sullivan", "Sean Osullivan"],
    "CBR": ["Kaeo Weekes", "Jed Stuart", "Simi Sasagi", "Matthew Timoko", "Xavier Savage", "Ethan Strange", "Ethan Sanders", "Josh Papalii", "Owen Pattie", "Joseph Tapine", "Zac Hosking", "Matty Nicholson", "Ata Mariota", "Tom Starling", "Joe Roddy", "Corey Horsburgh", "Daine Laurie", "Vena Patuki-Case", "Vena Patuki Case", "Savelio Tamale"],
    "CRO": ["William Kennedy", "Sione Katoa", "Sione Katoa 2", "Mawene Hiroti", "Kayal Iro", "Ronaldo Mulitalo", "Niwhai Puru", "Nicholas Hynes", "Addin Fonua-Blake", "Addin Fonua Blake", "Blayke Brailey", "Jesse Colquhoun", "Briton Nikora", "Teig Wilton", "Cameron McInnes", "Cameron Mcinnes", "Siosifa Talakai", "Billy Burns", "Oregon Kaufusi", "Thomas Hazelton", "Hohepa Puru", "Samuel Stonestreet"],
    "DOL": ["Hamiso Tabuai-Fidow", "Hamiso Tabuai Fidow", "Jamayne Isaako", "Jack Bostock", "Herbie Farnworth", "Selwyn Cobbo", "Kodi Nikorima", "Isaiya Katoa", "Thomas Flegler", "Jeremy Marshall-King", "Jeremy Marshall King", "Tom Gilbert", "Kulikefu Finefeuiaki", "Brian Pouniu", "Morgan Knowles", "Max Plath", "Ray Stone", "Francis Molo", "Felise Kaufusi", "Brad Schneider", "Jake Averillo"],
    "GLD": ["Keano Kini", "Jaylan De Groot", "Jojo Fifita", "Alexander Brimson", "Phillip Sami", "Jayden Campbell", "Lachlan Ilias", "Moeaki Fotuaika", "Oliver Pascoe", "Tino Fa'asuamaleaui", "Tino Faasuamaleaui", "Arama Hau", "Beau Fermor", "Cooper Bai", "Kurtis Morrin", "Klese Haas", "Chris Randall", "Bodhi Sharpley", "Luke Sommerton", "Siale Faeamani"],
    "MAN": ["Tom Trbojevic", "Jason Saab", "Tolutau Koula", "Reuben Garrick", "Lehi Hopoate", "Clayton Faulalo", "Jamal Fogarty", "Simione Laiafi", "Brandon Wakeham", "Nathan Brown", "Haumole Olakau'atu", "Haumole Olakauatu", "Ben Trbojevic", "Jake Trbojevic", "Jake Simpkin", "Nicholas Lenaz", "Corey Waddell", "Caleb Navale", "Josh Feledy", "Fletcher Baker"],
    "MEL": ["Sualauvi Faalogo", "Siulagi Tuimalatu-Brown", "Siulagi Tuimalatu Brown", "Jack Howarth", "Nick Meaney", "Moses Leo", "Cameron Munster", "Tyran Wishart", "Stefano Utoikamanu", "Harry Grant", "Josh King", "Shawn Blore", "Oryn Keeley", "Trent Loiero", "Alec MacDonald", "Alec Macdonald", "Angus Hinchey", "Cooper Clarke", "Trent Toelau", "Joe Chan", "Jack Hetherington"],
    "NEW": ["Kalyn Ponga", "Dominic Young", "Fletcher Hunt", "Bradman Best", "Greg Marzhew", "Fletcher Sharpe", "Sandon Smith", "Trey Mooney", "Phoenix Crossland", "Cody Hopwood", "Jermaine McEwen", "Jermaine Mcewen", "Tyson Frizell", "Mat Croker", "Jacob Saifiti", "Harrison Graham", "Lachlan Crouch", "Thomas Cant", "Toby Winter", "Elijah Salesa-Leaumoana", "Elijah Salesa Leaumoana"],
    "NZW": ["Taine Tuaupiki", "Dallin Watene-Zelezniak", "Dallin Watene Zelezniak", "Leka Halasima", "Adam Pompey", "Alofiana Khan-Pereira", "Alofiana Khan Pereira", "Luke Hanson", "Chanel Harris-Tavita", "Chanel Harris Tavita", "James Fisher-Harris", "James Fisher Harris", "Wayde Egan", "Mitchell Barnett", "Kurt Capewell", "Jacob Laban", "Erin Clark", "Ali Leiataua", "Samuel Healey", "Tanner Stowers-Smith", "Tanner Stowers Smith", "Demitric Vaimauga", "Eddie Ieremia-Toeava", "Eddie Ieremia Toeava", "Jett Cleary"],
    "PAR": ["Sean Russell", "Brian Kelly", "Te Hurinui Twidle", "Will Penisini", "Josh Addo-Carr", "Josh Addo Carr", "Ronald Volkman", "Mitchell Moses", "Luca Moretti", "Tallyn Da Silva", "Junior Paulo", "Jack Williams", "Kitione Kautoga", "Saxon Pryke", "Harrison Edwards", "Teancum Brown", "Jezaiah Funa-Iuta", "Jezaiah Funa Iuta", "Kelma Tuilagi", "Jordan Samrani", "Jack de Belin", "Jack De Belin"],
    "PEN": ["Dylan Edwards", "Thomas Jenkins", "Izack Tago", "Casey McLean", "Casey Mclean", "Brian To'o", "Brian Too", "Jack Cogger", "Nathan Cleary", "Moses Leota", "Freddy Lussick", "Liam Henry", "Isaiah Papali'i", "Isaiah Papalii", "Liam Martin", "Lindsay Smith", "Billy Scott", "Scott Sorensen", "Billy Phillips", "Luke Garner", "Luron Patea", "Jack Cole"],
    "SOU": ["Matt Dufty", "Alex Johnston", "Tallis Duncan", "Jack Wighton", "Campbell Graham", "Cody Walker", "Jayden Sullivan", "Tevita Tatola", "Brandon Smith", "Keaon Koloamatangi", "David Fifita", "Euan Aitken", "Cameron Murray", "Jye Gray", "Lachlan Hubner", "Sean Keppie", "Liam Le Blanc", "Peter Mamouzelos", "Edward Kosi"],
    "STI": ["Daniel Atkinson", "Mathew Feagai", "Moses Suli", "Valentine Holmes", "Tyrell Sloan", "Lyhkan King-Togia", "Lyhkan King Togia", "Kyle Flanagan", "Loko Pasifiki Tonga", "Jacob Liddle", "Toby Couchman", "Dylan Egan", "Hamish Stewart", "Ryan Couchman", "Damien Cook", "Jacob Halangahu", "Jacob Webster", "Setu Tu", "Josh Kerr", "Blake Lawrie"],
    "SYD": ["Cody Ramsey", "Billy Smith", "Hugo Savala", "Robert Toia", "Mark Nawaqanitawase", "Daly Cherry-Evans", "Daly Cherry Evans", "Sam Walker", "Naufahu Whyte", "Reece Robson", "Spencer Leniu", "Salesi Foketi", "Siua Wong", "Victor Radley", "Connor Watson", "Lindsay Collins", "Nat Butcher", "Egan Butcher", "Tommy Talau", "Rex Bassingthwaighte"],
    "WST": ["Jahream Bula", "Junior Tupou", "Solomone Saukuru", "Patrick Herbert", "Jeral Skelton", "Jarome Luai", "Jock Madden", "Terrell May", "Apisai Koroisau", "Fonua Pole", "Samuela Fainu", "Tony Sukkar", "Alex Twal", "Heath Mason", "Sione Fainu", "Alex Seyfarth", "Bunty Afoa", "Tristan Hope", "Tino Tavana"]
  }
};
