/* Auto-generated by cloud_fetch.py — DO NOT hand-edit (overwritten each run).
 * The family footytips comp snapshot: standings + each member's picks for
 * the round (picks appear as games lock / the round starts), plus the
 * per-round history (margins/scores/mpreds) and the fitted behavioural
 * pick model (beh) the finals solver needs. Powers the comp-aware tip
 * policy; front-end live-refreshes the standings between runs. */
window.NRL_COMP = {
 "round": 28,
 "roundIndexed": true,
 "finishRound": 31,
 "fetched": "2026-09-12T15:32:18+00:00",
 "members": [
  {
   "name": "Claire with an i",
   "me": false,
   "aff": {
    "NEW": [
     11,
     24
    ],
    "NQL": [
     18,
     24
    ],
    "CAN": [
     10,
     24
    ],
    "STI": [
     8,
     24
    ],
    "MEL": [
     7,
     24
    ],
    "PAR": [
     3,
     24
    ],
    "NZW": [
     18,
     24
    ],
    "SYD": [
     12,
     24
    ],
    "BRI": [
     5,
     24
    ],
    "PEN": [
     23,
     24
    ],
    "CRO": [
     14,
     24
    ],
    "GLD": [
     2,
     24
    ],
    "MAN": [
     21,
     24
    ],
    "CBR": [
     13,
     24
    ],
    "DOL": [
     17,
     24
    ],
    "SOU": [
     13,
     24
    ],
    "WST": [
     9,
     24
    ]
   },
   "rank": 1,
   "mv": "",
   "roundScore": 2,
   "totalScore": 134,
   "totalMargin": 492,
   "margins": [
    16,
    14,
    10,
    23,
    28,
    26,
    26,
    11,
    8,
    26,
    14,
    18,
    16,
    8,
    36,
    4,
    10,
    12,
    20,
    12,
    0,
    76,
    12,
    12,
    2,
    16,
    20,
    16
   ],
   "scores": [
    5,
    4,
    4,
    2,
    10,
    3,
    5,
    7,
    5,
    4,
    10,
    4,
    3,
    3,
    3,
    4,
    6,
    3,
    4,
    6,
    6,
    7,
    4,
    4,
    5,
    6,
    5,
    2
   ],
   "mpreds": [
    6,
    6,
    6,
    6,
    6,
    10,
    6,
    30,
    8,
    58,
    36,
    10,
    10,
    22,
    78,
    6,
    10,
    34,
    6,
    10,
    6,
    6,
    10,
    6,
    6,
    10,
    6,
    6
   ],
   "picks": {
    "NEW-SOU": "SOU",
    "DOL-NZW": "DOL",
    "CRO-NQL": "CRO"
   },
   "beh": {
    "a": 0.6701,
    "b": 0.7712,
    "loy": 3.9568,
    "n": 204,
    "hit": 0.7794
   }
  },
  {
   "name": "Brigitte",
   "me": true,
   "aff": {
    "NEW": [
     12,
     24
    ],
    "NQL": [
     15,
     24
    ],
    "CAN": [
     15,
     23
    ],
    "STI": [
     3,
     24
    ],
    "MEL": [
     10,
     24
    ],
    "PAR": [
     4,
     22
    ],
    "NZW": [
     23,
     24
    ],
    "SYD": [
     24,
     24
    ],
    "BRI": [
     5,
     23
    ],
    "PEN": [
     18,
     22
    ],
    "CRO": [
     14,
     24
    ],
    "GLD": [
     1,
     24
    ],
    "MAN": [
     15,
     24
    ],
    "CBR": [
     10,
     24
    ],
    "DOL": [
     16,
     24
    ],
    "SOU": [
     10,
     24
    ],
    "WST": [
     6,
     24
    ]
   },
   "rank": 2,
   "mv": "",
   "roundScore": 2,
   "totalScore": 133,
   "totalMargin": 476,
   "margins": [
    14,
    8,
    0,
    9,
    42,
    16,
    36,
    15,
    12,
    28,
    20,
    4,
    10,
    10,
    38,
    2,
    16,
    18,
    22,
    6,
    6,
    66,
    18,
    2,
    4,
    22,
    18,
    14
   ],
   "scores": [
    5,
    5,
    4,
    3,
    5,
    3,
    5,
    6,
    6,
    7,
    7,
    4,
    1,
    6,
    2,
    5,
    6,
    3,
    3,
    5,
    6,
    10,
    5,
    5,
    5,
    6,
    3,
    2
   ],
   "mpreds": [
    4,
    null,
    4,
    8,
    8,
    null,
    4,
    34,
    4,
    60,
    42,
    4,
    4,
    24,
    80,
    4,
    4,
    40,
    4,
    4,
    null,
    4,
    4,
    4,
    4,
    4,
    4,
    4
   ],
   "picks": {
    "NEW-SOU": "SOU",
    "DOL-NZW": "DOL",
    "CRO-NQL": "CRO"
   },
   "beh": {
    "a": 0.1131,
    "b": 1.4331,
    "loy": 3.9707,
    "n": 201,
    "hit": 0.8259
   }
  },
  {
   "name": "Thorners69",
   "me": false,
   "aff": {
    "NEW": [
     10,
     24
    ],
    "NQL": [
     9,
     23
    ],
    "CAN": [
     10,
     24
    ],
    "STI": [
     5,
     24
    ],
    "MEL": [
     13,
     23
    ],
    "PAR": [
     6,
     24
    ],
    "NZW": [
     16,
     24
    ],
    "SYD": [
     22,
     24
    ],
    "BRI": [
     9,
     24
    ],
    "PEN": [
     19,
     23
    ],
    "CRO": [
     18,
     24
    ],
    "GLD": [
     6,
     23
    ],
    "MAN": [
     11,
     23
    ],
    "CBR": [
     15,
     24
    ],
    "DOL": [
     13,
     23
    ],
    "SOU": [
     11,
     24
    ],
    "WST": [
     8,
     24
    ]
   },
   "rank": 3,
   "mv": "",
   "roundScore": 0,
   "totalScore": 130,
   "totalMargin": 515,
   "margins": [
    20,
    23,
    2,
    9,
    34,
    26,
    40,
    13,
    8,
    26,
    14,
    16,
    16,
    6,
    32,
    8,
    12,
    30,
    18,
    10,
    2,
    60,
    22,
    2,
    8,
    18,
    22,
    18
   ],
   "scores": [
    4,
    6,
    4,
    3,
    4,
    3,
    5,
    6,
    6,
    6,
    5,
    3,
    4,
    6,
    2,
    4,
    6,
    4,
    5,
    7,
    6,
    7,
    5,
    5,
    4,
    6,
    4,
    0
   ],
   "mpreds": [
    10,
    15,
    2,
    8,
    null,
    10,
    8,
    32,
    8,
    58,
    36,
    8,
    10,
    20,
    74,
    10,
    8,
    8,
    8,
    8,
    4,
    10,
    null,
    4,
    null,
    8,
    8,
    8
   ],
   "picks": {
    "NEW-SOU": "SOU",
    "DOL-NZW": "NZW",
    "CRO-NQL": "NQL"
   },
   "beh": {
    "a": 0.3658,
    "b": 0.8919,
    "loy": 2.0969,
    "n": 201,
    "hit": 0.6965
   }
  },
  {
   "name": "Jake",
   "me": false,
   "aff": {
    "MEL": [
     13,
     24
    ],
    "PAR": [
     4,
     24
    ],
    "NZW": [
     18,
     24
    ],
    "SYD": [
     18,
     24
    ],
    "BRI": [
     8,
     24
    ],
    "PEN": [
     24,
     24
    ],
    "CRO": [
     15,
     24
    ],
    "GLD": [
     2,
     24
    ],
    "MAN": [
     12,
     23
    ],
    "CBR": [
     11,
     23
    ],
    "DOL": [
     15,
     22
    ],
    "SOU": [
     14,
     23
    ],
    "WST": [
     12,
     23
    ],
    "NQL": [
     11,
     23
    ],
    "STI": [
     2,
     22
    ],
    "NEW": [
     10,
     22
    ],
    "CAN": [
     9,
     23
    ]
   },
   "rank": 4,
   "mv": "",
   "roundScore": 0,
   "totalScore": 128,
   "totalMargin": 492,
   "margins": [
    10,
    35,
    2,
    2,
    48,
    26,
    36,
    11,
    22,
    12,
    10,
    8,
    22,
    14,
    34,
    2,
    6,
    6,
    10,
    20,
    8,
    66,
    6,
    20,
    0,
    4,
    30,
    22
   ],
   "scores": [
    4,
    6,
    6,
    3,
    5,
    2,
    5,
    7,
    5,
    6,
    6,
    3,
    3,
    6,
    3,
    3,
    6,
    3,
    4,
    4,
    6,
    10,
    5,
    3,
    4,
    6,
    4,
    0
   ],
   "mpreds": [
    null,
    27,
    2,
    15,
    14,
    10,
    4,
    30,
    6,
    44,
    32,
    null,
    16,
    null,
    76,
    null,
    14,
    28,
    16,
    18,
    14,
    4,
    16,
    14,
    8,
    22,
    16,
    12
   ],
   "picks": {
    "NEW-SOU": "SOU",
    "DOL-NZW": "NZW",
    "CRO-NQL": "NQL"
   },
   "beh": {
    "a": 0.5242,
    "b": 1.243,
    "loy": 2.9263,
    "n": 198,
    "hit": 0.7576
   }
  },
  {
   "name": "Special unit",
   "me": false,
   "aff": {
    "NEW": [
     11,
     24
    ],
    "NQL": [
     13,
     24
    ],
    "CAN": [
     14,
     23
    ],
    "STI": [
     3,
     24
    ],
    "MEL": [
     15,
     24
    ],
    "PAR": [
     4,
     23
    ],
    "NZW": [
     17,
     24
    ],
    "SYD": [
     24,
     24
    ],
    "BRI": [
     8,
     23
    ],
    "PEN": [
     18,
     21
    ],
    "CRO": [
     15,
     23
    ],
    "GLD": [
     2,
     24
    ],
    "MAN": [
     13,
     23
    ],
    "CBR": [
     9,
     24
    ],
    "DOL": [
     11,
     22
    ],
    "SOU": [
     14,
     22
    ],
    "WST": [
     7,
     24
    ]
   },
   "rank": 5,
   "mv": "",
   "roundScore": 3,
   "totalScore": 123,
   "totalMargin": 506,
   "margins": [
    16,
    20,
    12,
    7,
    34,
    30,
    39,
    11,
    24,
    24,
    22,
    0,
    14,
    6,
    34,
    10,
    12,
    22,
    16,
    2,
    6,
    68,
    18,
    4,
    4,
    21,
    22,
    8
   ],
   "scores": [
    4,
    5,
    3,
    3,
    7,
    3,
    4,
    6,
    4,
    5,
    5,
    4,
    1,
    6,
    2,
    6,
    5,
    2,
    3,
    4,
    6,
    6,
    4,
    7,
    4,
    6,
    5,
    3
   ],
   "mpreds": [
    6,
    12,
    8,
    10,
    null,
    14,
    7,
    30,
    8,
    56,
    null,
    8,
    8,
    20,
    76,
    12,
    8,
    null,
    10,
    null,
    null,
    2,
    4,
    2,
    4,
    5,
    8,
    2
   ],
   "picks": {
    "NEW-SOU": "NEW",
    "DOL-NZW": "DOL",
    "CRO-NQL": "CRO"
   },
   "beh": {
    "a": 0.3626,
    "b": 0.9009,
    "loy": 3.7098,
    "n": 198,
    "hit": 0.7727
   }
  },
  {
   "name": "Susie loo",
   "me": false,
   "aff": {
    "NEW": [
     17,
     24
    ],
    "NQL": [
     13,
     24
    ],
    "CAN": [
     20,
     24
    ],
    "STI": [
     6,
     24
    ],
    "MEL": [
     7,
     24
    ],
    "PAR": [
     1,
     24
    ],
    "NZW": [
     12,
     24
    ],
    "SYD": [
     8,
     24
    ],
    "BRI": [
     6,
     24
    ],
    "PEN": [
     23,
     24
    ],
    "CRO": [
     11,
     24
    ],
    "GLD": [
     4,
     24
    ],
    "MAN": [
     24,
     24
    ],
    "CBR": [
     14,
     24
    ],
    "DOL": [
     15,
     24
    ],
    "SOU": [
     14,
     24
    ],
    "WST": [
     9,
     24
    ]
   },
   "rank": 6,
   "mv": "",
   "roundScore": 2,
   "totalScore": 113,
   "totalMargin": 541,
   "margins": [
    6,
    18,
    4,
    25,
    33,
    36,
    28,
    23,
    20,
    24,
    30,
    12,
    14,
    8,
    38,
    2,
    16,
    14,
    16,
    10,
    2,
    74,
    14,
    10,
    10,
    30,
    18,
    6
   ],
   "scores": [
    5,
    4,
    3,
    2,
    7,
    3,
    5,
    5,
    4,
    6,
    5,
    4,
    3,
    4,
    2,
    3,
    7,
    2,
    3,
    5,
    5,
    4,
    4,
    3,
    5,
    4,
    4,
    2
   ],
   "mpreds": [
    16,
    10,
    0,
    8,
    1,
    20,
    4,
    4,
    4,
    56,
    8,
    4,
    8,
    22,
    80,
    4,
    4,
    36,
    10,
    8,
    4,
    4,
    8,
    4,
    18,
    4,
    4,
    4
   ],
   "picks": {
    "NEW-SOU": "NEW",
    "DOL-NZW": "DOL",
    "CRO-NQL": "NQL"
   },
   "beh": {
    "a": 0.4898,
    "b": 0.317,
    "loy": 5.0834,
    "n": 204,
    "hit": 0.8137
   }
  }
 ]
};
