// Auto-generated by parse_nrl.py — DO NOT hand-edit (edits will be overwritten next run).
// To regenerate: python3 parse_nrl.py --ladder ladder_dump.html --draw draw_dump.html --out nrl_data.js --season 2026 --source zerotackle.com [--odds odds_dump.txt] [--injuries injuries_dump.txt]
// (see sources.md for where to fetch fresh dumps).
// Data current to end of Round 25, 2026.
// Schema v3: teams add colour/home/away/news; fixtures add city/odds/h2h.
// fixture.odds carries {open,close} decimal-odds snapshots for CLV
// (closing-line-value); `open` is carried forward run-to-run within a round.
// The legacy flat {home,away} shape and null are still accepted everywhere.
// fixture.weather is retired (2026-08-04) — kept as null for one deploy
// cycle for CDN-cached old pages, then the key can be dropped.
// Time-sensitive fields (odds, news) stay null unless the optional
// --odds/--injuries dumps are supplied that week.
window.NRL_DATA = {
  "updated": "2026-08-24",
  "season": 2026,
  "round": 26,
  "source": "zerotackle.com",
  "teams": [
    {
      "name": "Warriors",
      "short": "NZW",
      "colour": "#231f20",
      "P": 22,
      "W": 16,
      "L": 6,
      "PF": 651,
      "PA": 356,
      "last5": 4,
      "home": {
        "P": 10,
        "W": 8,
        "L": 2,
        "PF": 280,
        "PA": 160
      },
      "away": {
        "P": 12,
        "W": 8,
        "L": 4,
        "PF": 371,
        "PA": 196
      },
      "news": "Dallin Watene-Zelezniak (Shoulder); Ali Leiataua (Illness) — back Round 26; Te Maire Martin (Hamstring) — back Round 26; Charnze Nicoll-Klokstad (Suspension) — back Round 27; Jackson Ford (Pectoral) — back Finals; Luke Metcalf (Hamstring) — back Finals"
    },
    {
      "name": "Panthers",
      "short": "PEN",
      "colour": "#0a0a0a",
      "P": 22,
      "W": 16,
      "L": 6,
      "PF": 621,
      "PA": 327,
      "last5": 3,
      "home": {
        "P": 10,
        "W": 8,
        "L": 2,
        "PF": 286,
        "PA": 134
      },
      "away": {
        "P": 12,
        "W": 8,
        "L": 4,
        "PF": 335,
        "PA": 193
      },
      "news": "Paul Alamoti (Hamstring); Isaah Yeo (Pectoral); Mitch Kenny (Leg) — back Finals"
    },
    {
      "name": "Roosters",
      "short": "SYD",
      "colour": "#e2231a",
      "P": 22,
      "W": 16,
      "L": 6,
      "PF": 587,
      "PA": 425,
      "last5": 4,
      "home": {
        "P": 11,
        "W": 8,
        "L": 3,
        "PF": 259,
        "PA": 205
      },
      "away": {
        "P": 11,
        "W": 8,
        "L": 3,
        "PF": 328,
        "PA": 220
      },
      "news": "Daniel Tupou (Shoulder) — back Round 26; James Tedesco (Ankle) — back Round 26; Angus Crichton (Foot) — back Round 26; Blake Steep (ACL) — back Next Season"
    },
    {
      "name": "Dolphins",
      "short": "DOL",
      "colour": "#ee3524",
      "P": 22,
      "W": 15,
      "L": 7,
      "PF": 612,
      "PA": 474,
      "last5": 5,
      "home": {
        "P": 12,
        "W": 8,
        "L": 4,
        "PF": 344,
        "PA": 315
      },
      "away": {
        "P": 10,
        "W": 7,
        "L": 3,
        "PF": 268,
        "PA": 159
      },
      "news": "Kurt Donoghoe (Thumb) — back Round 26; Connelly Lemuelu (Hamstring) — back Round 27"
    },
    {
      "name": "Sharks",
      "short": "CRO",
      "colour": "#00a9e0",
      "P": 22,
      "W": 14,
      "L": 8,
      "PF": 634,
      "PA": 461,
      "last5": 3,
      "home": {
        "P": 11,
        "W": 8,
        "L": 3,
        "PF": 342,
        "PA": 222
      },
      "away": {
        "P": 11,
        "W": 6,
        "L": 5,
        "PF": 292,
        "PA": 239
      },
      "news": "Braydon Trindall (Shoulder); Jesse Ramien (Pectoral) — back Next Season"
    },
    {
      "name": "Knights",
      "short": "NEW",
      "colour": "#00539b",
      "P": 23,
      "W": 14,
      "L": 9,
      "PF": 601,
      "PA": 545,
      "last5": 3,
      "home": {
        "P": 12,
        "W": 8,
        "L": 4,
        "PF": 283,
        "PA": 303
      },
      "away": {
        "P": 11,
        "W": 6,
        "L": 5,
        "PF": 318,
        "PA": 242
      },
      "news": "Dane Gagai (Hamstring); Brodie Jones (Hamstring); Francis Manuleleua (Concussion) — back Round 26; Dylan Lucas (Ankle) — back Next Season; Dylan Brown (ACL) — back Next Season"
    },
    {
      "name": "Rabbitohs",
      "short": "SOU",
      "colour": "#00954c",
      "P": 22,
      "W": 12,
      "L": 10,
      "PF": 602,
      "PA": 539,
      "last5": 3,
      "home": {
        "P": 11,
        "W": 8,
        "L": 3,
        "PF": 318,
        "PA": 257
      },
      "away": {
        "P": 11,
        "W": 4,
        "L": 7,
        "PF": 284,
        "PA": 282
      },
      "news": "Jamie Humphreys (Ankle); Dayne Jennings (Knee); Talanoa Penitani (Hamstring) — back Round 26; Latrell Mitchell (Calf) — back Round 26; Adam Elliott (Groin) — back Round 27; Ashton Ward (Hamstring) — back Next Season"
    },
    {
      "name": "Cowboys",
      "short": "NQL",
      "colour": "#002b5c",
      "P": 22,
      "W": 12,
      "L": 10,
      "PF": 514,
      "PA": 592,
      "last5": 2,
      "home": {
        "P": 10,
        "W": 6,
        "L": 4,
        "PF": 240,
        "PA": 307
      },
      "away": {
        "P": 12,
        "W": 6,
        "L": 6,
        "PF": 274,
        "PA": 285
      },
      "news": "Tom Dearden (Ankle) — back Round 26; Jeremiah Nanai (Hamstring) — back Round 26"
    },
    {
      "name": "Bulldogs",
      "short": "CAN",
      "colour": "#00337f",
      "P": 22,
      "W": 11,
      "L": 11,
      "PF": 446,
      "PA": 478,
      "last5": 3,
      "home": {
        "P": 11,
        "W": 7,
        "L": 4,
        "PF": 204,
        "PA": 194
      },
      "away": {
        "P": 11,
        "W": 4,
        "L": 7,
        "PF": 242,
        "PA": 284
      },
      "news": "Enari Tuala (Knee); Sitili Tupouniua (Hamstring); Jethro Rinakama (Knee); Kurt Mann (Groin); Samuel Hughes (Neck)"
    },
    {
      "name": "Sea Eagles",
      "short": "MAN",
      "colour": "#6f1a3c",
      "P": 22,
      "W": 10,
      "L": 12,
      "PF": 549,
      "PA": 483,
      "last5": 1,
      "home": {
        "P": 11,
        "W": 5,
        "L": 6,
        "PF": 225,
        "PA": 237
      },
      "away": {
        "P": 11,
        "W": 5,
        "L": 6,
        "PF": 324,
        "PA": 246
      },
      "news": "Ethan Bullemor (Concussion); Tolutau Koula (Ankle); Siosiua Taukeiaho (Leg); Joey Walsh (Jaw); Taniela Paseka (Knee) — back Round 26; Kobe Hetherington (Biceps) — back Next Season"
    },
    {
      "name": "Storm",
      "short": "MEL",
      "colour": "#4b2e83",
      "P": 22,
      "W": 9,
      "L": 13,
      "PF": 524,
      "PA": 536,
      "last5": 1,
      "home": {
        "P": 12,
        "W": 7,
        "L": 5,
        "PF": 322,
        "PA": 274
      },
      "away": {
        "P": 10,
        "W": 2,
        "L": 8,
        "PF": 202,
        "PA": 262
      },
      "news": "Jahrome Hughes (Hamstring); Tui Kamikamica (Medical Episode); Ativalu Lisati (Ankle); Eliesa Katoa (Medical Episode) — back Indefinite; Will Warbrick (Achilles) — back Next Season; Xavier Coates (Achilles) — back Next Season"
    },
    {
      "name": "Raiders",
      "short": "CBR",
      "colour": "#8bc53f",
      "P": 23,
      "W": 10,
      "L": 13,
      "PF": 531,
      "PA": 596,
      "last5": 2,
      "home": {
        "P": 12,
        "W": 5,
        "L": 7,
        "PF": 292,
        "PA": 282
      },
      "away": {
        "P": 11,
        "W": 5,
        "L": 6,
        "PF": 239,
        "PA": 314
      },
      "news": "Zac Hosking (Hamstring); Morgan Smithies (Head knock) — back Round 26; Noah Martin (Quad) — back Round 26; Hudson Young (Achilles) — back Next Season"
    },
    {
      "name": "Eels",
      "short": "PAR",
      "colour": "#006eb5",
      "P": 22,
      "W": 8,
      "L": 14,
      "PF": 437,
      "PA": 636,
      "last5": 2,
      "home": {
        "P": 11,
        "W": 5,
        "L": 6,
        "PF": 220,
        "PA": 296
      },
      "away": {
        "P": 11,
        "W": 3,
        "L": 8,
        "PF": 217,
        "PA": 340
      },
      "news": "Jordan Samrani (Groin); Dylan Walker (Wrist) — back Round 26; J'maine Hopgood (ACL) — back Next Season; Matt Doorey (Knee) — back Next Season; Isaiah Iongi (Knee) — back Next Season"
    },
    {
      "name": "Wests Tigers",
      "short": "WST",
      "colour": "#f68b1f",
      "P": 22,
      "W": 8,
      "L": 14,
      "PF": 425,
      "PA": 637,
      "last5": 1,
      "home": {
        "P": 12,
        "W": 5,
        "L": 7,
        "PF": 278,
        "PA": 339
      },
      "away": {
        "P": 10,
        "W": 3,
        "L": 7,
        "PF": 147,
        "PA": 298
      },
      "news": "Royce Hunt (Pectoral); Sunia Turuva (Knee); Alex Twal (Head knock); Latu Fainu (Hamstring) — back Round 26; Adam Doueihi (Shoulder) — back Next Season; Taylan May (Shoulder) — back Next Season"
    },
    {
      "name": "Broncos",
      "short": "BRI",
      "colour": "#6c1d45",
      "P": 22,
      "W": 7,
      "L": 15,
      "PF": 417,
      "PA": 611,
      "last5": 1,
      "home": {
        "P": 11,
        "W": 2,
        "L": 9,
        "PF": 216,
        "PA": 305
      },
      "away": {
        "P": 11,
        "W": 5,
        "L": 6,
        "PF": 201,
        "PA": 306
      },
      "news": "Adam Reynolds (Calf); Reece Walsh (Ankle); Preston Riki (Ankle); Brendan Piakura (Concussion); Cory Paix (Shoulder) — back Next Season"
    },
    {
      "name": "Titans",
      "short": "GLD",
      "colour": "#fbb040",
      "P": 22,
      "W": 6,
      "L": 16,
      "PF": 435,
      "PA": 597,
      "last5": 1,
      "home": {
        "P": 10,
        "W": 3,
        "L": 7,
        "PF": 163,
        "PA": 286
      },
      "away": {
        "P": 12,
        "W": 3,
        "L": 9,
        "PF": 272,
        "PA": 311
      },
      "news": "Beau Fermor (Abdomen); Brock Gray (ACL); Dean Ieremia (Hamstring); Josh Patston (Head knock) — back Round 26; Jaimin Jolliffe (Knee) — back Next Season; Jensen Taumoepeau (Ankle) — back Next Season"
    },
    {
      "name": "Dragons",
      "short": "STI",
      "colour": "#e2231a",
      "P": 22,
      "W": 4,
      "L": 18,
      "PF": 358,
      "PA": 651,
      "last5": 2,
      "home": {
        "P": 11,
        "W": 2,
        "L": 9,
        "PF": 178,
        "PA": 378
      },
      "away": {
        "P": 11,
        "W": 2,
        "L": 9,
        "PF": 180,
        "PA": 273
      },
      "news": "Hame Sele (Achilles); Jacob Liddle (Calf); Jaydn Su'A (Pectoral) — back Round 27; Hayden Buchanan (Shoulder) — back Next Season; David Fale (Calf) — back Next Season; Clinton Gutherson (Knee) — back Next Season"
    }
  ],
  "fixtures": [
    {
      "home": "BRI",
      "away": "MEL",
      "venue": "Suncorp Stadium",
      "city": "Brisbane",
      "kickoff": "2026-08-27T19:50:00+10:00",
      "odds": {
        "open": {
          "home": 1.83,
          "away": 1.95
        },
        "close": {
          "home": 1.83,
          "away": 1.95
        }
      },
      "weather": null,
      "h2h": null,
      "tz": "Australia/Brisbane"
    },
    {
      "home": "MAN",
      "away": "STI",
      "venue": "4 Pines Park",
      "city": "Sydney",
      "kickoff": "2026-08-28T18:00:00+10:00",
      "odds": {
        "open": {
          "home": 1.42,
          "away": 2.85
        },
        "close": {
          "home": 1.42,
          "away": 2.85
        }
      },
      "weather": null,
      "h2h": null,
      "tz": "Australia/Sydney"
    },
    {
      "home": "PEN",
      "away": "CAN",
      "venue": "CommBank Stadium",
      "city": "Sydney",
      "kickoff": "2026-08-28T20:00:00+10:00",
      "odds": {
        "open": {
          "home": 1.36,
          "away": 3.1
        },
        "close": {
          "home": 1.36,
          "away": 3.1
        }
      },
      "weather": null,
      "h2h": null,
      "tz": "Australia/Sydney"
    },
    {
      "home": "GLD",
      "away": "SOU",
      "venue": "Cbus Super Stadium",
      "city": "Gold Coast",
      "kickoff": "2026-08-29T15:00:00+10:00",
      "odds": {
        "open": {
          "home": 2.88,
          "away": 1.4
        },
        "close": {
          "home": 2.88,
          "away": 1.4
        }
      },
      "weather": null,
      "h2h": null,
      "tz": "Australia/Brisbane"
    },
    {
      "home": "SYD",
      "away": "DOL",
      "venue": "Allianz Stadium",
      "city": "Sydney",
      "kickoff": "2026-08-29T17:30:00+10:00",
      "odds": {
        "open": {
          "home": 1.55,
          "away": 2.45
        },
        "close": {
          "home": 1.55,
          "away": 2.45
        }
      },
      "weather": null,
      "h2h": null,
      "tz": "Australia/Sydney"
    },
    {
      "home": "NQL",
      "away": "WST",
      "venue": "Queensland Country Bank Stadium",
      "city": "Townsville",
      "kickoff": "2026-08-29T19:35:00+10:00",
      "odds": {
        "open": {
          "home": 1.29,
          "away": 3.58
        },
        "close": {
          "home": 1.29,
          "away": 3.58
        }
      },
      "weather": null,
      "h2h": null,
      "tz": "Australia/Brisbane"
    },
    {
      "home": "NZW",
      "away": "NEW",
      "venue": "Go Media Stadium",
      "city": "Auckland",
      "kickoff": "2026-08-30T16:00:00+12:00",
      "odds": {
        "open": {
          "home": 1.4,
          "away": 2.92
        },
        "close": {
          "home": 1.4,
          "away": 2.92
        }
      },
      "weather": null,
      "h2h": null,
      "tz": "Pacific/Auckland"
    },
    {
      "home": "PAR",
      "away": "CRO",
      "venue": "CommBank Stadium",
      "city": "Sydney",
      "kickoff": "2026-08-30T16:05:00+10:00",
      "odds": {
        "open": {
          "home": 2.75,
          "away": 1.44
        },
        "close": {
          "home": 2.75,
          "away": 1.44
        }
      },
      "weather": null,
      "h2h": null,
      "tz": "Australia/Sydney"
    }
  ],
  "byeTeams": [
    "CBR"
  ],
  "generatedAt": "2026-08-24T03:01:52+10:00",
  "changes": [],
  "changesSince": "2026-08-23T23:49:00+10:00"
};
