// Auto-generated by parse_nrl.py — DO NOT hand-edit (edits will be overwritten next run).
// To regenerate: python3 parse_nrl.py --ladder ladder_dump.html --draw draw_dump.html --out nrl_data.js --season 2026 --source zerotackle.com [--odds odds_dump.txt] [--injuries injuries_dump.txt]
// (see sources.md for where to fetch fresh dumps).
// Data current to end of Round 25, 2026.
// Schema v3: teams add colour/home/away/news; fixtures add city/odds/h2h.
// fixture.odds carries {open,close} decimal-odds snapshots for CLV
// (closing-line-value); `open` is carried forward run-to-run within a round.
// The legacy flat {home,away} shape and null are still accepted everywhere.
// fixture.weather is retired (2026-08-04) — kept as null for one deploy
// cycle for CDN-cached old pages, then the key can be dropped.
// Time-sensitive fields (odds, news) stay null unless the optional
// --odds/--injuries dumps are supplied that week.
window.NRL_DATA = {
  "updated": "2026-08-26",
  "season": 2026,
  "round": 26,
  "source": "zerotackle.com",
  "teams": [
    {
      "name": "Warriors",
      "short": "NZW",
      "colour": "#231f20",
      "P": 22,
      "W": 16,
      "L": 6,
      "PF": 651,
      "PA": 356,
      "last5": 4,
      "home": {
        "P": 10,
        "W": 8,
        "L": 2,
        "PF": 280,
        "PA": 160
      },
      "away": {
        "P": 12,
        "W": 8,
        "L": 4,
        "PF": 371,
        "PA": 196
      },
      "news": "Te Maire Martin (Hamstring) — back Round 26; Ali Leiataua (Illness) — back Round 26; Charnze Nicoll-Klokstad (Suspension) — back Round 27; Jackson Ford (Pectoral) — back Finals; Luke Metcalf (Hamstring) — back Finals; Dallin Watene-Zelezniak (Collarbone) — back Finals"
    },
    {
      "name": "Panthers",
      "short": "PEN",
      "colour": "#0a0a0a",
      "P": 22,
      "W": 16,
      "L": 6,
      "PF": 621,
      "PA": 327,
      "last5": 3,
      "home": {
        "P": 10,
        "W": 8,
        "L": 2,
        "PF": 286,
        "PA": 134
      },
      "away": {
        "P": 12,
        "W": 8,
        "L": 4,
        "PF": 335,
        "PA": 193
      },
      "news": "Isaah Yeo (Pectoral); Paul Alamoti (Hamstring); Mitch Kenny (Leg) — back Finals; Jack Cogger (Suspension) — back Finals"
    },
    {
      "name": "Roosters",
      "short": "SYD",
      "colour": "#e2231a",
      "P": 22,
      "W": 16,
      "L": 6,
      "PF": 587,
      "PA": 425,
      "last5": 4,
      "home": {
        "P": 11,
        "W": 8,
        "L": 3,
        "PF": 259,
        "PA": 205
      },
      "away": {
        "P": 11,
        "W": 8,
        "L": 3,
        "PF": 328,
        "PA": 220
      },
      "news": "Angus Crichton (Foot) — back Round 26; James Tedesco (Ankle) — back Round 26; Daniel Tupou (Shoulder) — back Round 26; Victor Radley (Concussion) — back Round 27; Blake Steep (ACL) — back Next Season"
    },
    {
      "name": "Dolphins",
      "short": "DOL",
      "colour": "#ee3524",
      "P": 22,
      "W": 15,
      "L": 7,
      "PF": 612,
      "PA": 474,
      "last5": 5,
      "home": {
        "P": 12,
        "W": 8,
        "L": 4,
        "PF": 344,
        "PA": 315
      },
      "away": {
        "P": 10,
        "W": 7,
        "L": 3,
        "PF": 268,
        "PA": 159
      },
      "news": "Kurt Donoghoe (Thumb) — back Round 26; Connelly Lemuelu (Hamstring) — back Round 27"
    },
    {
      "name": "Sharks",
      "short": "CRO",
      "colour": "#00a9e0",
      "P": 22,
      "W": 14,
      "L": 8,
      "PF": 634,
      "PA": 461,
      "last5": 3,
      "home": {
        "P": 11,
        "W": 8,
        "L": 3,
        "PF": 342,
        "PA": 222
      },
      "away": {
        "P": 11,
        "W": 6,
        "L": 5,
        "PF": 292,
        "PA": 239
      },
      "news": "Braydon Trindall (Shoulder); Jesse Ramien (Pectoral) — back Next Season"
    },
    {
      "name": "Knights",
      "short": "NEW",
      "colour": "#00539b",
      "P": 23,
      "W": 14,
      "L": 9,
      "PF": 601,
      "PA": 545,
      "last5": 3,
      "home": {
        "P": 12,
        "W": 8,
        "L": 4,
        "PF": 283,
        "PA": 303
      },
      "away": {
        "P": 11,
        "W": 6,
        "L": 5,
        "PF": 318,
        "PA": 242
      },
      "news": "Dane Gagai (Hamstring) — back Round 26; Francis Manuleleua (Concussion) — back Round 26; Brodie Jones (Hamstring) — back Round 26; Dominic Young (Suspension) — back Finals; Tyson Frizell (Suspension) — back Finals; Phoenix Crossland (Knee) — back Finals"
    },
    {
      "name": "Rabbitohs",
      "short": "SOU",
      "colour": "#00954c",
      "P": 22,
      "W": 12,
      "L": 10,
      "PF": 602,
      "PA": 539,
      "last5": 3,
      "home": {
        "P": 11,
        "W": 8,
        "L": 3,
        "PF": 318,
        "PA": 257
      },
      "away": {
        "P": 11,
        "W": 4,
        "L": 7,
        "PF": 284,
        "PA": 282
      },
      "news": "Dayne Jennings (Knee); Jamie Humphreys (Ankle) — back Round 26; Latrell Mitchell (Calf) — back Round 26; Talanoa Penitani (Hamstring) — back Round 26; Adam Elliott (Groin) — back Round 26; Ashton Ward (Hamstring) — back Next Season"
    },
    {
      "name": "Cowboys",
      "short": "NQL",
      "colour": "#002b5c",
      "P": 22,
      "W": 12,
      "L": 10,
      "PF": 514,
      "PA": 592,
      "last5": 2,
      "home": {
        "P": 10,
        "W": 6,
        "L": 4,
        "PF": 240,
        "PA": 307
      },
      "away": {
        "P": 12,
        "W": 6,
        "L": 6,
        "PF": 274,
        "PA": 285
      },
      "news": "Murray Taulagi (Concussion); Jeremiah Nanai (Hamstring) — back Round 26; Tom Dearden (Ankle) — back Round 26"
    },
    {
      "name": "Bulldogs",
      "short": "CAN",
      "colour": "#00337f",
      "P": 22,
      "W": 11,
      "L": 11,
      "PF": 446,
      "PA": 478,
      "last5": 3,
      "home": {
        "P": 11,
        "W": 7,
        "L": 4,
        "PF": 204,
        "PA": 194
      },
      "away": {
        "P": 11,
        "W": 4,
        "L": 7,
        "PF": 242,
        "PA": 284
      },
      "news": "Sitili Tupouniua (Hamstring); Jethro Rinakama (Knee); Kurt Mann (Groin); Samuel Hughes (Neck); Enari Tuala (Knee) — back Round 26; Jonathan Sua (Suspension) — back Round 27"
    },
    {
      "name": "Sea Eagles",
      "short": "MAN",
      "colour": "#6f1a3c",
      "P": 22,
      "W": 10,
      "L": 12,
      "PF": 549,
      "PA": 483,
      "last5": 1,
      "home": {
        "P": 11,
        "W": 5,
        "L": 6,
        "PF": 225,
        "PA": 237
      },
      "away": {
        "P": 11,
        "W": 5,
        "L": 6,
        "PF": 324,
        "PA": 246
      },
      "news": "Ethan Bullemor (Concussion); Tolutau Koula (Ankle); Siosiua Taukeiaho (Leg); Joey Walsh (Jaw); Taniela Paseka (Knee) — back Round 26; Luke Brooks (ACL) — back Next Season"
    },
    {
      "name": "Storm",
      "short": "MEL",
      "colour": "#4b2e83",
      "P": 22,
      "W": 9,
      "L": 13,
      "PF": 524,
      "PA": 536,
      "last5": 1,
      "home": {
        "P": 12,
        "W": 7,
        "L": 5,
        "PF": 322,
        "PA": 274
      },
      "away": {
        "P": 10,
        "W": 2,
        "L": 8,
        "PF": 202,
        "PA": 262
      },
      "news": "Jahrome Hughes (Hamstring); Ativalu Lisati (Ankle); Eliesa Katoa (Medical Episode) — back Indefinite; Xavier Coates (Achilles) — back Next Season; Jack Howarth (Shoulder) — back Next Season; Will Warbrick (Achilles) — back Next Season"
    },
    {
      "name": "Raiders",
      "short": "CBR",
      "colour": "#8bc53f",
      "P": 23,
      "W": 10,
      "L": 13,
      "PF": 531,
      "PA": 596,
      "last5": 2,
      "home": {
        "P": 12,
        "W": 5,
        "L": 7,
        "PF": 292,
        "PA": 282
      },
      "away": {
        "P": 11,
        "W": 5,
        "L": 6,
        "PF": 239,
        "PA": 314
      },
      "news": "Noah Martin (Quad) — back Round 26; Morgan Smithies (Head knock) — back Round 26; Zac Hosking (Hamstring) — back Next Season; Hudson Young (Achilles) — back Next Season"
    },
    {
      "name": "Eels",
      "short": "PAR",
      "colour": "#006eb5",
      "P": 22,
      "W": 8,
      "L": 14,
      "PF": 437,
      "PA": 636,
      "last5": 2,
      "home": {
        "P": 11,
        "W": 5,
        "L": 6,
        "PF": 220,
        "PA": 296
      },
      "away": {
        "P": 11,
        "W": 3,
        "L": 8,
        "PF": 217,
        "PA": 340
      },
      "news": "Dylan Walker (Wrist) — back Round 26; Jordan Samrani (Groin) — back Round 27; Matt Doorey (Knee) — back Next Season; Isaiah Iongi (Knee) — back Next Season; J'maine Hopgood (ACL) — back Next Season"
    },
    {
      "name": "Wests Tigers",
      "short": "WST",
      "colour": "#f68b1f",
      "P": 22,
      "W": 8,
      "L": 14,
      "PF": 425,
      "PA": 637,
      "last5": 1,
      "home": {
        "P": 12,
        "W": 5,
        "L": 7,
        "PF": 278,
        "PA": 339
      },
      "away": {
        "P": 10,
        "W": 3,
        "L": 7,
        "PF": 147,
        "PA": 298
      },
      "news": "Royce Hunt (Pectoral); Sunia Turuva (Knee) — back Round 26; Latu Fainu (Hamstring) — back Round 26; Alex Twal (Concussion) — back Round 27; Adam Doueihi (Shoulder) — back Next Season; Taylan May (Shoulder) — back Next Season"
    },
    {
      "name": "Broncos",
      "short": "BRI",
      "colour": "#6c1d45",
      "P": 22,
      "W": 7,
      "L": 15,
      "PF": 417,
      "PA": 611,
      "last5": 1,
      "home": {
        "P": 11,
        "W": 2,
        "L": 9,
        "PF": 216,
        "PA": 305
      },
      "away": {
        "P": 11,
        "W": 5,
        "L": 6,
        "PF": 201,
        "PA": 306
      },
      "news": "Preston Riki (Ankle); Brendan Piakura (Concussion); Reece Walsh (Ankle); Cory Paix (Shoulder) — back Next Season"
    },
    {
      "name": "Titans",
      "short": "GLD",
      "colour": "#fbb040",
      "P": 22,
      "W": 6,
      "L": 16,
      "PF": 435,
      "PA": 597,
      "last5": 1,
      "home": {
        "P": 10,
        "W": 3,
        "L": 7,
        "PF": 163,
        "PA": 286
      },
      "away": {
        "P": 12,
        "W": 3,
        "L": 9,
        "PF": 272,
        "PA": 311
      },
      "news": "Beau Fermor (Ribs); Dean Ieremia (Hamstring); Brock Gray (ACL); Josh Patston (Head knock) — back Round 26; Jensen Taumoepeau (Ankle) — back Next Season; Jaimin Jolliffe (Knee) — back Next Season"
    },
    {
      "name": "Dragons",
      "short": "STI",
      "colour": "#e2231a",
      "P": 22,
      "W": 4,
      "L": 18,
      "PF": 358,
      "PA": 651,
      "last5": 2,
      "home": {
        "P": 11,
        "W": 2,
        "L": 9,
        "PF": 178,
        "PA": 378
      },
      "away": {
        "P": 11,
        "W": 2,
        "L": 9,
        "PF": 180,
        "PA": 273
      },
      "news": "Hame Sele (Achilles); Jacob Liddle (Calf); Jaydn Su'A (Pectoral) — back Round 27; Hayden Buchanan (Shoulder) — back Next Season; Clinton Gutherson (Knee) — back Next Season; David Fale (Calf) — back Next Season"
    }
  ],
  "fixtures": [
    {
      "home": "BRI",
      "away": "MEL",
      "venue": "Suncorp Stadium",
      "city": "Brisbane",
      "kickoff": "2026-08-27T19:50:00+10:00",
      "odds": {
        "open": {
          "home": 1.83,
          "away": 1.95
        },
        "close": {
          "home": 2.25,
          "away": 1.65
        }
      },
      "weather": null,
      "h2h": null,
      "tz": "Australia/Brisbane"
    },
    {
      "home": "MAN",
      "away": "STI",
      "venue": "4 Pines Park",
      "city": "Sydney",
      "kickoff": "2026-08-28T18:00:00+10:00",
      "odds": {
        "open": {
          "home": 1.42,
          "away": 2.85
        },
        "close": {
          "home": 1.4,
          "away": 2.94
        }
      },
      "weather": null,
      "h2h": null,
      "tz": "Australia/Sydney"
    },
    {
      "home": "PEN",
      "away": "CAN",
      "venue": "CommBank Stadium",
      "city": "Sydney",
      "kickoff": "2026-08-28T20:00:00+10:00",
      "odds": {
        "open": {
          "home": 1.36,
          "away": 3.1
        },
        "close": {
          "home": 1.35,
          "away": 3.2
        }
      },
      "weather": null,
      "h2h": null,
      "tz": "Australia/Sydney"
    },
    {
      "home": "GLD",
      "away": "SOU",
      "venue": "Cbus Super Stadium",
      "city": "Gold Coast",
      "kickoff": "2026-08-29T15:00:00+10:00",
      "odds": {
        "open": {
          "home": 2.88,
          "away": 1.4
        },
        "close": {
          "home": 3.35,
          "away": 1.33
        }
      },
      "weather": null,
      "h2h": null,
      "tz": "Australia/Brisbane"
    },
    {
      "home": "SYD",
      "away": "DOL",
      "venue": "Allianz Stadium",
      "city": "Sydney",
      "kickoff": "2026-08-29T17:30:00+10:00",
      "odds": {
        "open": {
          "home": 1.55,
          "away": 2.45
        },
        "close": {
          "home": 1.55,
          "away": 2.45
        }
      },
      "weather": null,
      "h2h": null,
      "tz": "Australia/Sydney"
    },
    {
      "home": "NQL",
      "away": "WST",
      "venue": "Queensland Country Bank Stadium",
      "city": "Townsville",
      "kickoff": "2026-08-29T19:35:00+10:00",
      "odds": {
        "open": {
          "home": 1.29,
          "away": 3.58
        },
        "close": {
          "home": 1.26,
          "away": 3.8
        }
      },
      "weather": null,
      "h2h": null,
      "tz": "Australia/Brisbane"
    },
    {
      "home": "NZW",
      "away": "NEW",
      "venue": "Go Media Stadium",
      "city": "Auckland",
      "kickoff": "2026-08-30T16:00:00+12:00",
      "odds": {
        "open": {
          "home": 1.4,
          "away": 2.92
        },
        "close": {
          "home": 1.28,
          "away": 3.7
        }
      },
      "weather": null,
      "h2h": null,
      "tz": "Pacific/Auckland"
    },
    {
      "home": "PAR",
      "away": "CRO",
      "venue": "CommBank Stadium",
      "city": "Sydney",
      "kickoff": "2026-08-30T16:05:00+10:00",
      "odds": {
        "open": {
          "home": 2.75,
          "away": 1.44
        },
        "close": {
          "home": 2.6,
          "away": 1.49
        }
      },
      "weather": null,
      "h2h": null,
      "tz": "Australia/Sydney"
    }
  ],
  "byeTeams": [
    "CBR"
  ],
  "generatedAt": "2026-08-26T15:59:07+10:00",
  "changes": [
    {
      "id": "r26-NEW-inj-phoenix-crossland",
      "fixture": "NZW-NEW",
      "team": "NEW",
      "cat": "injury",
      "sev": 3,
      "dir": "down",
      "text": "Knights: Phoenix Crossland (Knee) — back Finals — new on the injury list.",
      "pts": 3.1,
      "ts": "2026-08-25T18:24:56+10:00",
      "rnd": 26
    },
    {
      "id": "r26-BRI-MEL-line-2.21-1.64",
      "fixture": "BRI-MEL",
      "team": "MEL",
      "cat": "line",
      "sev": 2,
      "dir": "up",
      "text": "Line moved — Broncos $1.95 → $2.21, Storm $1.85 → $1.64. Market now 43% Broncos (was 49%).",
      "pts": null,
      "ts": "2026-08-25T18:24:56+10:00",
      "rnd": 26
    },
    {
      "id": "r26-NEW-fit-dylan-lucas",
      "fixture": "NZW-NEW",
      "team": "NEW",
      "cat": "injury",
      "sev": 2,
      "dir": "up",
      "text": "Knights: Dylan Lucas is off the injury list.",
      "pts": 2.0,
      "ts": "2026-08-25T18:24:56+10:00",
      "rnd": 26
    },
    {
      "id": "r26-NQL-inj-murray-taulagi",
      "fixture": "NQL-WST",
      "team": "NQL",
      "cat": "injury",
      "sev": 2,
      "dir": "down",
      "text": "Cowboys: Murray Taulagi (Concussion) — new on the injury list.",
      "pts": 1.9,
      "ts": "2026-08-25T18:24:56+10:00",
      "rnd": 26
    },
    {
      "id": "r26-MEL-inj-jack-howarth",
      "fixture": "BRI-MEL",
      "team": "MEL",
      "cat": "injury",
      "sev": 2,
      "dir": "down",
      "text": "Storm: Jack Howarth (Shoulder) — back Next Season — new on the injury list.",
      "pts": 1.7,
      "ts": "2026-08-25T18:24:56+10:00",
      "rnd": 26
    },
    {
      "id": "r26-MEL-fit-tui-kamikamica",
      "fixture": "BRI-MEL",
      "team": "MEL",
      "cat": "injury",
      "sev": 2,
      "dir": "up",
      "text": "Storm: Tui Kamikamica is off the injury list.",
      "pts": 1.0,
      "ts": "2026-08-25T15:53:06+10:00",
      "rnd": 26
    },
    {
      "id": "r26-MAN-STI-line-1.40-2.94",
      "fixture": "MAN-STI",
      "team": "STI",
      "cat": "line",
      "sev": 1,
      "dir": "up",
      "text": "Line moved — Sea Eagles $1.40 → $1.40, Dragons $2.95 → $2.94. Market now 68% Sea Eagles (was 68%).",
      "pts": null,
      "ts": "2026-08-26T15:59:07+10:00",
      "rnd": 26
    },
    {
      "id": "r26-GLD-SOU-line-3.35-1.33",
      "fixture": "GLD-SOU",
      "team": null,
      "cat": "line",
      "sev": 1,
      "dir": "neutral",
      "text": "Line moved — Titans $3.20 → $3.35, Rabbitohs $1.33 → $1.33. Market now 28% Titans (was 29%).",
      "pts": null,
      "ts": "2026-08-26T15:59:07+10:00",
      "rnd": 26
    },
    {
      "id": "r26-BRI-MEL-line-2.25-1.65",
      "fixture": "BRI-MEL",
      "team": "MEL",
      "cat": "line",
      "sev": 1,
      "dir": "up",
      "text": "Line moved — Broncos $2.20 → $2.25, Storm $1.66 → $1.65. Market now 42% Broncos (was 43%).",
      "pts": null,
      "ts": "2026-08-26T13:38:50+10:00",
      "rnd": 26
    },
    {
      "id": "r26-MAN-STI-line-1.40-2.95",
      "fixture": "MAN-STI",
      "team": null,
      "cat": "line",
      "sev": 1,
      "dir": "neutral",
      "text": "Line moved — Sea Eagles $1.40 → $1.40, Dragons $2.93 → $2.95. Market now 68% Sea Eagles (was 68%).",
      "pts": null,
      "ts": "2026-08-26T13:38:50+10:00",
      "rnd": 26
    },
    {
      "id": "r26-GLD-SOU-line-3.20-1.33",
      "fixture": "GLD-SOU",
      "team": "SOU",
      "cat": "line",
      "sev": 1,
      "dir": "up",
      "text": "Line moved — Titans $3.10 → $3.20, Rabbitohs $1.36 → $1.33. Market now 29% Titans (was 30%).",
      "pts": null,
      "ts": "2026-08-26T13:38:50+10:00",
      "rnd": 26
    },
    {
      "id": "r26-NQL-WST-line-1.26-3.80",
      "fixture": "NQL-WST",
      "team": "NQL",
      "cat": "line",
      "sev": 1,
      "dir": "up",
      "text": "Line moved — Cowboys $1.27 → $1.26, Wests Tigers $3.78 → $3.80. Market now 75% Cowboys (was 75%).",
      "pts": null,
      "ts": "2026-08-26T13:38:50+10:00",
      "rnd": 26
    },
    {
      "id": "r26-NZW-NEW-line-1.28-3.70",
      "fixture": "NZW-NEW",
      "team": "NZW",
      "cat": "line",
      "sev": 1,
      "dir": "up",
      "text": "Line moved — Warriors $1.29 → $1.28, Knights $3.55 → $3.70. Market now 74% Warriors (was 73%).",
      "pts": null,
      "ts": "2026-08-26T13:38:50+10:00",
      "rnd": 26
    },
    {
      "id": "r26-BRI-MEL-line-2.20-1.66",
      "fixture": "BRI-MEL",
      "team": "BRI",
      "cat": "line",
      "sev": 1,
      "dir": "up",
      "text": "Line moved — Broncos $2.21 → $2.20, Storm $1.65 → $1.66. Market now 43% Broncos (was 43%).",
      "pts": null,
      "ts": "2026-08-26T07:14:15+10:00",
      "rnd": 26
    },
    {
      "id": "r26-NQL-WST-line-1.27-3.78",
      "fixture": "NQL-WST",
      "team": null,
      "cat": "line",
      "sev": 1,
      "dir": "neutral",
      "text": "Line moved — Cowboys $1.27 → $1.27, Wests Tigers $3.76 → $3.78. Market now 75% Cowboys (was 75%).",
      "pts": null,
      "ts": "2026-08-26T07:14:15+10:00",
      "rnd": 26
    },
    {
      "id": "r26-NZW-NEW-line-1.29-3.55",
      "fixture": "NZW-NEW",
      "team": null,
      "cat": "line",
      "sev": 1,
      "dir": "neutral",
      "text": "Line moved — Warriors $1.29 → $1.29, Knights $3.52 → $3.55. Market now 73% Warriors (was 73%).",
      "pts": null,
      "ts": "2026-08-26T07:14:15+10:00",
      "rnd": 26
    },
    {
      "id": "r26-BRI-MEL-line-2.21-1.65",
      "fixture": "BRI-MEL",
      "team": "BRI",
      "cat": "line",
      "sev": 1,
      "dir": "up",
      "text": "Line moved — Broncos $2.23 → $2.21, Storm $1.63 → $1.65. Market now 43% Broncos (was 42%).",
      "pts": null,
      "ts": "2026-08-26T06:58:50+10:00",
      "rnd": 26
    },
    {
      "id": "r26-GLD-SOU-line-3.10-1.36",
      "fixture": "GLD-SOU",
      "team": "GLD",
      "cat": "line",
      "sev": 1,
      "dir": "up",
      "text": "Line moved — Titans $3.12 → $3.10, Rabbitohs $1.36 → $1.36. Market now 30% Titans (was 30%).",
      "pts": null,
      "ts": "2026-08-26T00:30:57+10:00",
      "rnd": 26
    },
    {
      "id": "r26-BRI-MEL-line-2.23-1.63",
      "fixture": "BRI-MEL",
      "team": "MEL",
      "cat": "line",
      "sev": 1,
      "dir": "up",
      "text": "Line moved — Broncos $2.21 → $2.23, Storm $1.64 → $1.63. Market now 42% Broncos (was 43%).",
      "pts": null,
      "ts": "2026-08-25T20:00:23+10:00",
      "rnd": 26
    },
    {
      "id": "r26-MAN-STI-line-1.40-2.92",
      "fixture": "MAN-STI",
      "team": "STI",
      "cat": "line",
      "sev": 1,
      "dir": "up",
      "text": "Line moved — Sea Eagles $1.40 → $1.40, Dragons $2.93 → $2.92. Market now 68% Sea Eagles (was 68%).",
      "pts": null,
      "ts": "2026-08-25T20:00:23+10:00",
      "rnd": 26
    },
    {
      "id": "r26-PEN-CAN-line-1.33-3.33",
      "fixture": "PEN-CAN",
      "team": "PEN",
      "cat": "line",
      "sev": 1,
      "dir": "up",
      "text": "Line moved — Panthers $1.35 → $1.33, Bulldogs $3.20 → $3.33. Market now 71% Panthers (was 70%).",
      "pts": null,
      "ts": "2026-08-25T20:00:23+10:00",
      "rnd": 26
    },
    {
      "id": "r26-GLD-SOU-line-3.12-1.36",
      "fixture": "GLD-SOU",
      "team": "GLD",
      "cat": "line",
      "sev": 1,
      "dir": "up",
      "text": "Line moved — Titans $3.15 → $3.12, Rabbitohs $1.36 → $1.36. Market now 30% Titans (was 30%).",
      "pts": null,
      "ts": "2026-08-25T20:00:23+10:00",
      "rnd": 26
    },
    {
      "id": "r26-NZW-NEW-line-1.29-3.52",
      "fixture": "NZW-NEW",
      "team": "NZW",
      "cat": "line",
      "sev": 1,
      "dir": "up",
      "text": "Line moved — Warriors $1.30 → $1.29, Knights $3.40 → $3.52. Market now 73% Warriors (was 72%).",
      "pts": null,
      "ts": "2026-08-25T20:00:23+10:00",
      "rnd": 26
    },
    {
      "id": "r26-PAR-CRO-line-2.62-1.48",
      "fixture": "PAR-CRO",
      "team": "CRO",
      "cat": "line",
      "sev": 1,
      "dir": "up",
      "text": "Line moved — Eels $2.60 → $2.62, Sharks $1.49 → $1.48. Market now 36% Eels (was 36%).",
      "pts": null,
      "ts": "2026-08-25T20:00:23+10:00",
      "rnd": 26
    },
    {
      "id": "r26-MAN-STI-line-1.40-2.93",
      "fixture": "MAN-STI",
      "team": null,
      "cat": "line",
      "sev": 1,
      "dir": "neutral",
      "text": "Line moved — Sea Eagles $1.40 → $1.40, Dragons $2.91 → $2.93. Market now 68% Sea Eagles (was 68%).",
      "pts": null,
      "ts": "2026-08-25T18:24:56+10:00",
      "rnd": 26
    },
    {
      "id": "r26-PEN-CAN-line-1.35-3.20",
      "fixture": "PEN-CAN",
      "team": "CAN",
      "cat": "line",
      "sev": 1,
      "dir": "up",
      "text": "Line moved — Panthers $1.30 → $1.35, Bulldogs $3.50 → $3.20. Market now 70% Panthers (was 73%).",
      "pts": null,
      "ts": "2026-08-25T18:24:56+10:00",
      "rnd": 26
    },
    {
      "id": "r26-GLD-SOU-line-3.15-1.36",
      "fixture": "GLD-SOU",
      "team": "SOU",
      "cat": "line",
      "sev": 1,
      "dir": "up",
      "text": "Line moved — Titans $3.02 → $3.15, Rabbitohs $1.38 → $1.36. Market now 30% Titans (was 31%).",
      "pts": null,
      "ts": "2026-08-25T18:24:56+10:00",
      "rnd": 26
    },
    {
      "id": "r26-NQL-WST-line-1.27-3.75",
      "fixture": "NQL-WST",
      "team": null,
      "cat": "line",
      "sev": 1,
      "dir": "neutral",
      "text": "Line moved — Cowboys $1.27 → $1.27, Wests Tigers $3.67 → $3.75. Market now 75% Cowboys (was 74%).",
      "pts": null,
      "ts": "2026-08-25T18:24:56+10:00",
      "rnd": 26
    },
    {
      "id": "r26-NZW-NEW-line-1.30-3.40",
      "fixture": "NZW-NEW",
      "team": "NZW",
      "cat": "line",
      "sev": 1,
      "dir": "up",
      "text": "Line moved — Warriors $1.33 → $1.30, Knights $3.33 → $3.40. Market now 72% Warriors (was 71%).",
      "pts": null,
      "ts": "2026-08-25T18:24:56+10:00",
      "rnd": 26
    },
    {
      "id": "r26-PAR-CRO-line-2.60-1.49",
      "fixture": "PAR-CRO",
      "team": "PAR",
      "cat": "line",
      "sev": 1,
      "dir": "up",
      "text": "Line moved — Eels $2.67 → $2.60, Sharks $1.46 → $1.49. Market now 36% Eels (was 35%).",
      "pts": null,
      "ts": "2026-08-25T18:24:56+10:00",
      "rnd": 26
    },
    {
      "id": "r26-BRI-MEL-line-1.95-1.85",
      "fixture": "BRI-MEL",
      "team": "MEL",
      "cat": "line",
      "sev": 1,
      "dir": "up",
      "text": "Line moved — Broncos $1.95 → $1.95, Storm $1.86 → $1.85. Market now 49% Broncos (was 49%).",
      "pts": null,
      "ts": "2026-08-25T15:53:06+10:00",
      "rnd": 26
    },
    {
      "id": "r26-GLD-SOU-line-3.02-1.38",
      "fixture": "GLD-SOU",
      "team": null,
      "cat": "line",
      "sev": 1,
      "dir": "neutral",
      "text": "Line moved — Titans $2.98 → $3.02, Rabbitohs $1.38 → $1.38. Market now 31% Titans (was 32%).",
      "pts": null,
      "ts": "2026-08-25T15:53:06+10:00",
      "rnd": 26
    },
    {
      "id": "r26-BRI-MEL-line-1.95-1.86",
      "fixture": "BRI-MEL",
      "team": "MEL",
      "cat": "line",
      "sev": 1,
      "dir": "up",
      "text": "Line moved — Broncos $1.85 → $1.95, Storm $1.95 → $1.86. Market now 49% Broncos (was 51%).",
      "pts": null,
      "ts": "2026-08-25T13:27:51+10:00",
      "rnd": 26
    },
    {
      "id": "r26-MAN-STI-line-1.40-2.91",
      "fixture": "MAN-STI",
      "team": null,
      "cat": "line",
      "sev": 1,
      "dir": "neutral",
      "text": "Line moved — Sea Eagles $1.40 → $1.40, Dragons $2.90 → $2.91. Market now 68% Sea Eagles (was 67%).",
      "pts": null,
      "ts": "2026-08-25T13:27:51+10:00",
      "rnd": 26
    },
    {
      "id": "r26-PEN-CAN-line-1.30-3.50",
      "fixture": "PEN-CAN",
      "team": "PEN",
      "cat": "line",
      "sev": 1,
      "dir": "up",
      "text": "Line moved — Panthers $1.32 → $1.30, Bulldogs $3.35 → $3.50. Market now 73% Panthers (was 72%).",
      "pts": null,
      "ts": "2026-08-25T13:27:51+10:00",
      "rnd": 26
    },
    {
      "id": "r26-GLD-SOU-line-2.98-1.38",
      "fixture": "GLD-SOU",
      "team": "SOU",
      "cat": "line",
      "sev": 1,
      "dir": "up",
      "text": "Line moved — Titans $2.95 → $2.98, Rabbitohs $1.40 → $1.38. Market now 32% Titans (was 32%).",
      "pts": null,
      "ts": "2026-08-25T13:27:51+10:00",
      "rnd": 26
    },
    {
      "id": "r26-NZW-NEW-line-1.33-3.33",
      "fixture": "NZW-NEW",
      "team": "NZW",
      "cat": "line",
      "sev": 1,
      "dir": "up",
      "text": "Line moved — Warriors $1.40 → $1.33, Knights $2.95 → $3.33. Market now 71% Warriors (was 68%).",
      "pts": null,
      "ts": "2026-08-25T13:27:51+10:00",
      "rnd": 26
    },
    {
      "id": "r26-PAR-CRO-line-2.67-1.46",
      "fixture": "PAR-CRO",
      "team": "PAR",
      "cat": "line",
      "sev": 1,
      "dir": "up",
      "text": "Line moved — Eels $2.70 → $2.67, Sharks $1.46 → $1.46. Market now 35% Eels (was 35%).",
      "pts": null,
      "ts": "2026-08-25T13:27:51+10:00",
      "rnd": 26
    },
    {
      "id": "r26-PEN-CAN-line-1.32-3.35",
      "fixture": "PEN-CAN",
      "team": null,
      "cat": "line",
      "sev": 1,
      "dir": "neutral",
      "text": "Line moved — Panthers $1.32 → $1.32, Bulldogs $3.30 → $3.35. Market now 72% Panthers (was 71%).",
      "pts": null,
      "ts": "2026-08-25T07:48:45+10:00",
      "rnd": 26
    },
    {
      "id": "r26-BRI-MEL-line-1.87-1.95",
      "fixture": "BRI-MEL",
      "team": null,
      "cat": "line",
      "sev": 1,
      "dir": "neutral",
      "text": "Line moved — Broncos $1.86 → $1.87, Storm $1.95 → $1.95. Market now 51% Broncos (was 51%).",
      "pts": null,
      "ts": "2026-08-25T07:03:19+10:00",
      "rnd": 26
    },
    {
      "id": "r26-PEN-CAN-line-1.32-3.30",
      "fixture": "PEN-CAN",
      "team": "CAN",
      "cat": "line",
      "sev": 1,
      "dir": "up",
      "text": "Line moved — Panthers $1.32 → $1.32, Bulldogs $3.33 → $3.30. Market now 71% Panthers (was 72%).",
      "pts": null,
      "ts": "2026-08-25T07:03:19+10:00",
      "rnd": 26
    },
    {
      "id": "r26-NQL-WST-line-1.28-3.65",
      "fixture": "NQL-WST",
      "team": "WST",
      "cat": "line",
      "sev": 1,
      "dir": "up",
      "text": "Line moved — Cowboys $1.27 → $1.28, Wests Tigers $3.67 → $3.65. Market now 74% Cowboys (was 74%).",
      "pts": null,
      "ts": "2026-08-25T07:03:19+10:00",
      "rnd": 26
    }
  ],
  "changesSince": "2026-08-25T07:03:19+10:00"
};
