/* Auto-generated by freeze_tips.mjs — DO NOT hand-edit (overwritten each run).
 * The official pre-kick-off tip for each game, frozen by the pipeline so
 * full-time grading is identical on every device and can never use hindsight.
 * An entry stops changing the moment its game kicks off. */
window.NRL_TIPLOG = {
 "updated": "2026-08-14T21:03:48.650Z",
 "tips": [
  {
   "season": 2026,
   "round": 22,
   "home": "CRO",
   "away": "SOU",
   "tip": "CRO",
   "ko": "2026-08-02T14:00:00+10:00",
   "ts": "2026-08-01T23:43:45.006Z"
  },
  {
   "season": 2026,
   "round": 22,
   "home": "WST",
   "away": "PAR",
   "tip": "PAR",
   "ko": "2026-08-02T16:05:00+10:00",
   "ts": "2026-08-01T23:43:45.006Z"
  },
  {
   "season": 2026,
   "round": 23,
   "home": "CBR",
   "away": "NEW",
   "tip": "CBR",
   "prob": 55,
   "why": "Built on Knights missing Dylan Brown and 4 more, plus the home-ground edge. Raiders missing Hudson Young and 1 more pulls it back (and more). The bookies read it the same way.",
   "ko": "2026-08-09T14:00:00+10:00",
   "ts": "2026-08-08T21:50:47.728Z"
  },
  {
   "season": 2026,
   "round": 23,
   "home": "DOL",
   "away": "BRI",
   "tip": "DOL",
   "ko": "2026-08-08T17:30:00+10:00",
   "ts": "2026-08-08T07:07:18.177Z"
  },
  {
   "season": 2026,
   "round": 23,
   "home": "GLD",
   "away": "NQL",
   "tip": "NQL",
   "ko": "2026-08-06T19:50:00+10:00",
   "ts": "2026-08-05T23:36:13.882Z"
  },
  {
   "season": 2026,
   "round": 23,
   "home": "MEL",
   "away": "MAN",
   "tip": "MAN",
   "ko": null,
   "ts": "2026-08-08T07:07:18.177Z"
  },
  {
   "season": 2026,
   "round": 23,
   "home": "NZW",
   "away": "PEN",
   "tip": "PEN",
   "ko": "2026-08-07T20:00:00+12:00",
   "ts": "2026-08-07T04:36:09.119Z"
  },
  {
   "season": 2026,
   "round": 23,
   "home": "SOU",
   "away": "PAR",
   "tip": "SOU",
   "ko": null,
   "ts": "2026-08-08T11:19:40.305Z"
  },
  {
   "season": 2026,
   "round": 23,
   "home": "STI",
   "away": "CRO",
   "tip": "CRO",
   "prob": 85,
   "why": "Mostly Sharks rating the stronger side, plus Dragons missing Jaydn Su'A and 3 more. Sharks missing Siosifa Talakai and 1 more pulls it back (and more). The bookies read it the same way.",
   "ko": "2026-08-09T16:05:00+10:00",
   "ts": "2026-08-09T04:48:54.626Z"
  },
  {
   "season": 2026,
   "round": 23,
   "home": "SYD",
   "away": "CAN",
   "tip": "SYD",
   "ko": null,
   "ts": "2026-08-07T11:13:04.108Z"
  },
  {
   "season": 2026,
   "round": 24,
   "home": "BRI",
   "away": "NZW",
   "tip": "NZW",
   "prob": 70,
   "mkt": 67,
   "why": "Built on Warriors rating the stronger side, plus Broncos being without Adam Reynolds (not named) and 3 more. Warriors missing Tanah Boyd and 2 more pulls it back. The bookies read it the same way.",
   "ko": "2026-08-15T19:35:00+10:00",
   "ts": "2026-08-14T21:03:48.650Z"
  },
  {
   "season": 2026,
   "round": 24,
   "home": "CAN",
   "away": "SOU",
   "tip": "SOU",
   "prob": 39,
   "mkt": 40,
   "why": "Mostly Rabbitohs missing Ashton Ward and 4 more, plus the home-ground edge. Bulldogs being without Sitili Tupouniua (not named) and 1 more pulls it back. The bookies read it the same way.",
   "ko": "2026-08-14T20:00:00+10:00",
   "ts": "2026-08-14T05:50:41.229Z"
  },
  {
   "season": 2026,
   "round": 24,
   "home": "CRO",
   "away": "CBR",
   "tip": "CRO",
   "prob": 73,
   "mkt": 73,
   "why": "Built on Sharks rating the stronger side, plus Raiders missing Hudson Young and 2 more. Sharks missing Jesse Ramien and 1 more pulls it back. The bookies read it the same way.",
   "ko": "2026-08-15T15:00:00+10:00",
   "ts": "2026-08-14T21:03:48.650Z"
  },
  {
   "season": 2026,
   "round": 24,
   "home": "MAN",
   "away": "DOL",
   "tip": "DOL",
   "prob": 74,
   "mkt": 73,
   "why": "Built on Sea Eagles missing Tom Trbojevic and 5 more, plus Dolphins rating the stronger side. Dolphins missing Kurt Donoghoe pulls it back (and more). The bookies read it the same way.",
   "ko": "2026-08-14T18:00:00+10:00",
   "ts": "2026-08-14T05:50:41.229Z"
  },
  {
   "season": 2026,
   "round": 24,
   "home": "NEW",
   "away": "GLD",
   "tip": "NEW",
   "prob": 74,
   "mkt": 77,
   "why": "Built on Knights rating the stronger side, plus Titans missing Zane Harrison and 3 more. Knights missing Dylan Brown and 4 more pulls it back. The bookies read it the same way.",
   "ko": "2026-08-16T14:00:00+10:00",
   "ts": "2026-08-14T21:03:48.650Z"
  },
  {
   "season": 2026,
   "round": 24,
   "home": "PAR",
   "away": "NQL",
   "tip": "PAR",
   "prob": 37,
   "mkt": 38,
   "why": "Built on Eels missing Isaiah Iongi and 4 more, plus Cowboys rating the stronger side. Cowboys being without Tom Dearden (not named) and 1 more pulls it back. The bookies read it the same way.",
   "ko": "2026-08-15T17:30:00+10:00",
   "ts": "2026-08-14T21:03:48.650Z"
  },
  {
   "season": 2026,
   "round": 24,
   "home": "PEN",
   "away": "SYD",
   "tip": "SYD",
   "prob": 41,
   "mkt": 38,
   "why": "Built on Roosters missing James Tedesco and 3 more, plus the home-ground edge. Panthers missing Mitch Kenny and 2 more pulls it back (and more). The bookies read it the same way.",
   "ko": "2026-08-13T19:50:00+10:00",
   "ts": "2026-08-13T05:53:10.293Z"
  },
  {
   "season": 2026,
   "round": 24,
   "home": "WST",
   "away": "STI",
   "tip": "STI",
   "prob": 51,
   "mkt": 51,
   "why": "Built on Wests Tigers missing Latu Fainu and 3 more. Dragons missing Jaydn Su'A and 3 more pulls it back (and more). The bookies read it the same way.",
   "ko": "2026-08-16T16:05:00+10:00",
   "ts": "2026-08-14T21:03:48.650Z"
  }
 ],
 "flips": [
  {
   "season": 2026,
   "round": 24,
   "home": "CAN",
   "away": "SOU",
   "from": "CAN",
   "to": "SOU",
   "fromProb": 60,
   "toProb": 40,
   "why": "Mostly Rabbitohs missing Ashton Ward and 4 more, plus the home-ground edge. Bulldogs being without Sitili Tupouniua (not named) and 1 more pulls it back. The bookies read it the same way.",
   "ts": "2026-08-13T11:47:15.215Z"
  },
  {
   "season": 2026,
   "round": 24,
   "home": "PAR",
   "away": "NQL",
   "from": "NQL",
   "to": "PAR",
   "fromProb": 62,
   "toProb": 38,
   "why": "Built on Eels missing Isaiah Iongi and 4 more, plus Cowboys rating the stronger side. Cowboys being without Tom Dearden (not named) and 1 more pulls it back (and more). The bookies read it the same way.",
   "ts": "2026-08-13T11:47:15.215Z"
  }
 ]
};
