/* Auto-generated by freeze_tips.mjs — DO NOT hand-edit (overwritten each run).
 * The official pre-kick-off tip for each game, frozen by the pipeline so
 * full-time grading is identical on every device and can never use hindsight.
 * An entry stops changing the moment its game kicks off. */
window.NRL_TIPLOG = {
 "updated": "2026-08-09T14:19:19.788Z",
 "tips": [
  {
   "season": 2026,
   "round": 22,
   "home": "CRO",
   "away": "SOU",
   "tip": "CRO",
   "ko": "2026-08-02T14:00:00+10:00",
   "ts": "2026-08-01T23:43:45.006Z"
  },
  {
   "season": 2026,
   "round": 22,
   "home": "WST",
   "away": "PAR",
   "tip": "PAR",
   "ko": "2026-08-02T16:05:00+10:00",
   "ts": "2026-08-01T23:43:45.006Z"
  },
  {
   "season": 2026,
   "round": 23,
   "home": "CBR",
   "away": "NEW",
   "tip": "CBR",
   "prob": 55,
   "why": "Built on Knights missing Dylan Brown and 4 more, plus the home-ground edge. Raiders missing Hudson Young and 1 more pulls it back (and more). The bookies read it the same way.",
   "ko": "2026-08-09T14:00:00+10:00",
   "ts": "2026-08-08T21:50:47.728Z"
  },
  {
   "season": 2026,
   "round": 23,
   "home": "DOL",
   "away": "BRI",
   "tip": "DOL",
   "ko": "2026-08-08T17:30:00+10:00",
   "ts": "2026-08-08T07:07:18.177Z"
  },
  {
   "season": 2026,
   "round": 23,
   "home": "GLD",
   "away": "NQL",
   "tip": "NQL",
   "ko": "2026-08-06T19:50:00+10:00",
   "ts": "2026-08-05T23:36:13.882Z"
  },
  {
   "season": 2026,
   "round": 23,
   "home": "MEL",
   "away": "MAN",
   "tip": "MAN",
   "ko": null,
   "ts": "2026-08-08T07:07:18.177Z"
  },
  {
   "season": 2026,
   "round": 23,
   "home": "NZW",
   "away": "PEN",
   "tip": "PEN",
   "ko": "2026-08-07T20:00:00+12:00",
   "ts": "2026-08-07T04:36:09.119Z"
  },
  {
   "season": 2026,
   "round": 23,
   "home": "SOU",
   "away": "PAR",
   "tip": "SOU",
   "ko": null,
   "ts": "2026-08-08T11:19:40.305Z"
  },
  {
   "season": 2026,
   "round": 23,
   "home": "STI",
   "away": "CRO",
   "tip": "CRO",
   "prob": 85,
   "why": "Mostly Sharks rating the stronger side, plus Dragons missing Jaydn Su'A and 3 more. Sharks missing Siosifa Talakai and 1 more pulls it back (and more). The bookies read it the same way.",
   "ko": "2026-08-09T16:05:00+10:00",
   "ts": "2026-08-09T04:48:54.626Z"
  },
  {
   "season": 2026,
   "round": 23,
   "home": "SYD",
   "away": "CAN",
   "tip": "SYD",
   "ko": null,
   "ts": "2026-08-07T11:13:04.108Z"
  }
 ],
 "flips": []
};
