// Auto-generated by parse_nrl.py — safe to regenerate (see WEEKLY_UPDATE.md).
// To regenerate: python3 parse_nrl.py --ladder ladder_dump.html --draw draw_dump.html --out nrl_data.js --season 2026 --source zerotackle.com
// Data current to end of Round 21, 2026.
// Schema v3: adds home/away splits per team, and per-fixture odds/weather/h2h + per-team news.
// Time-sensitive fields (odds, weather, news) are null until the weekly Tuesday refresh fills them.
window.NRL_DATA = {
  "updated": "2026-07-27",
  "newsUpdated": "2026-07-27",
  "season": 2026,
  "round": 22,
  "source": "zerotackle.com",
  "teams": [
    { "name":"Panthers",     "short":"PEN", "colour":"#0a0a0a", "P":18, "W":14, "L":4,  "PF":539, "PA":255, "last5":2,
      "home":{"P":8,"W":7,"L":1,"PF":238,"PA":104}, "away":{"P":10,"W":7,"L":3,"PF":301,"PA":151}, "news":null },
    { "name":"Roosters",     "short":"SYD", "colour":"#e2231a", "P":18, "W":13, "L":5,  "PF":449, "PA":364, "last5":4,
      "home":{"P":9,"W":7,"L":2,"PF":215,"PA":162}, "away":{"P":9,"W":6,"L":3,"PF":234,"PA":202}, "news":null },
    { "name":"Warriors",     "short":"NZW", "colour":"#231f20", "P":18, "W":12, "L":6,  "PF":496, "PA":306, "last5":3,
      "home":{"P":9,"W":7,"L":2,"PF":252,"PA":148}, "away":{"P":9,"W":5,"L":4,"PF":244,"PA":158}, "news":null },
    { "name":"Sharks",       "short":"CRO", "colour":"#00a9e0", "P":17, "W":11, "L":6,  "PF":488, "PA":363, "last5":4,
      "home":{"P":9,"W":7,"L":2,"PF":290,"PA":182}, "away":{"P":8,"W":4,"L":4,"PF":198,"PA":181}, "news":null },
    { "name":"Dolphins",     "short":"DOL", "colour":"#ee3524", "P":18, "W":11, "L":7,  "PF":488, "PA":404, "last5":3,
      "home":{"P":10,"W":6,"L":4,"PF":270,"PA":267}, "away":{"P":8,"W":5,"L":3,"PF":218,"PA":137}, "news":null },
    { "name":"Rabbitohs",    "short":"SOU", "colour":"#00954c", "P":18, "W":10, "L":8,  "PF":510, "PA":432, "last5":3,
      "home":{"P":9,"W":7,"L":2,"PF":264,"PA":188}, "away":{"P":9,"W":3,"L":6,"PF":246,"PA":244}, "news":null },
    { "name":"Knights",      "short":"NEW", "colour":"#00539b", "P":19, "W":11, "L":8,  "PF":481, "PA":445, "last5":3,
      "home":{"P":10,"W":7,"L":3,"PF":223,"PA":233}, "away":{"P":9,"W":4,"L":5,"PF":258,"PA":212}, "news":null },
    { "name":"Cowboys",      "short":"NQL", "colour":"#002b5c", "P":19, "W":11, "L":8,  "PF":442, "PA":470, "last5":2,
      "home":{"P":9,"W":6,"L":3,"PF":228,"PA":225}, "away":{"P":10,"W":5,"L":5,"PF":214,"PA":245}, "news":null },
    { "name":"Sea Eagles",   "short":"MAN", "colour":"#6f1a3c", "P":18, "W":9,  "L":9,  "PF":473, "PA":347, "last5":2,
      "home":{"P":9,"W":5,"L":4,"PF":213,"PA":167}, "away":{"P":9,"W":4,"L":5,"PF":260,"PA":180}, "news":null },
    { "name":"Bulldogs",     "short":"CAN", "colour":"#00337f", "P":18, "W":9,  "L":9,  "PF":342, "PA":400, "last5":4,
      "home":{"P":10,"W":7,"L":3,"PF":198,"PA":172}, "away":{"P":8,"W":2,"L":6,"PF":144,"PA":228}, "news":null },
    { "name":"Raiders",      "short":"CBR", "colour":"#8bc53f", "P":19, "W":9,  "L":10, "PF":435, "PA":470, "last5":3,
      "home":{"P":10,"W":5,"L":5,"PF":238,"PA":218}, "away":{"P":9,"W":4,"L":5,"PF":197,"PA":252}, "news":null },
    { "name":"Storm",        "short":"MEL", "colour":"#4b2e83", "P":19, "W":8,  "L":11, "PF":446, "PA":458, "last5":3,
      "home":{"P":9,"W":6,"L":3,"PF":244,"PA":196}, "away":{"P":10,"W":2,"L":8,"PF":202,"PA":262}, "news":null },
    { "name":"Broncos",      "short":"BRI", "colour":"#6c1d45", "P":18, "W":6,  "L":12, "PF":339, "PA":471, "last5":1,
      "home":{"P":9,"W":2,"L":7,"PF":204,"PA":235}, "away":{"P":9,"W":4,"L":5,"PF":135,"PA":236}, "news":null },
    { "name":"Eels",         "short":"PAR", "colour":"#006eb5", "P":18, "W":6,  "L":12, "PF":349, "PA":531, "last5":2,
      "home":{"P":10,"W":4,"L":6,"PF":188,"PA":266}, "away":{"P":8,"W":2,"L":6,"PF":161,"PA":265}, "news":null },
    { "name":"Wests Tigers", "short":"WST", "colour":"#f68b1f", "P":19, "W":7,  "L":12, "PF":365, "PA":573, "last5":0,
      "home":{"P":10,"W":5,"L":5,"PF":243,"PA":299}, "away":{"P":9,"W":2,"L":7,"PF":122,"PA":274}, "news":null },
    { "name":"Titans",       "short":"GLD", "colour":"#fbb040", "P":17, "W":5,  "L":12, "PF":335, "PA":441, "last5":2,
      "home":{"P":7,"W":3,"L":4,"PF":127,"PA":184}, "away":{"P":10,"W":2,"L":8,"PF":208,"PA":257}, "news":null },
    { "name":"Dragons",      "short":"STI", "colour":"#e2231a", "P":17, "W":2,  "L":15, "PF":256, "PA":503, "last5":2,
      "home":{"P":7,"W":1,"L":6,"PF":100,"PA":252}, "away":{"P":10,"W":1,"L":9,"PF":156,"PA":251}, "news":null }
  ],
  "fixtures": [
    { "home":"NQL", "away":"SYD", "venue":"QLD Country Bank Stadium", "city":"Townsville",  "kickoff":"2026-07-30T19:50:00", "odds":null, "weather":null, "h2h":null },
    { "home":"PEN", "away":"CBR", "venue":"Glen Willow Oval, Mudgee", "city":"Mudgee",      "kickoff":"2026-08-01T17:30:00", "odds":null, "weather":null, "h2h":null },
    { "home":"GLD", "away":"NZW", "venue":"Cbus Super Stadium",       "city":"Gold Coast",  "kickoff":"2026-08-01T15:00:00", "odds":null, "weather":null, "h2h":null },
    { "home":"BRI", "away":"NEW", "venue":"Suncorp Stadium",          "city":"Brisbane",    "kickoff":"2026-08-01T19:35:00", "odds":null, "weather":null, "h2h":null },
    { "home":"MEL", "away":"CAN", "venue":"AAMI Park",                "city":"Melbourne",   "kickoff":"2026-07-31T19:50:00", "odds":null, "weather":null, "h2h":null },
    { "home":"STI", "away":"DOL", "venue":"WIN Stadium",              "city":"Wollongong",  "kickoff":"2026-07-31T18:00:00", "odds":null, "weather":null, "h2h":null },
    { "home":"CRO", "away":"SOU", "venue":"Sharks Stadium, Cronulla", "city":"Sydney",      "kickoff":"2026-08-02T14:00:00", "odds":null, "weather":null, "h2h":null },
    { "home":"PAR", "away":"WST", "venue":"CommBank Stadium",         "city":"Sydney",      "kickoff":"2026-08-02T16:05:00", "odds":null, "weather":null, "h2h":null }
  ],
  "byeTeams": ["MAN"]
};
