/* Auto-generated by cloud_fetch.py — DO NOT hand-edit (overwritten each run).
 * The family footytips comp snapshot: standings + each member's picks for
 * the round (picks appear as games lock / the round starts), plus the
 * per-round history (margins/scores/mpreds) and the fitted behavioural
 * pick model (beh) the finals solver needs. Powers the comp-aware tip
 * policy; front-end live-refreshes the standings between runs. */
window.NRL_COMP = {
 "round": 29,
 "roundIndexed": true,
 "finishRound": 31,
 "fetched": "2026-09-14T22:45:13+00:00",
 "members": [
  {
   "name": "Claire with an i",
   "me": false,
   "aff": {
    "NEW": [
     11,
     25
    ],
    "NQL": [
     18,
     25
    ],
    "CAN": [
     10,
     24
    ],
    "STI": [
     8,
     24
    ],
    "MEL": [
     7,
     24
    ],
    "PAR": [
     3,
     24
    ],
    "NZW": [
     18,
     25
    ],
    "SYD": [
     12,
     25
    ],
    "BRI": [
     5,
     24
    ],
    "PEN": [
     24,
     25
    ],
    "CRO": [
     15,
     25
    ],
    "GLD": [
     2,
     24
    ],
    "MAN": [
     21,
     24
    ],
    "CBR": [
     13,
     24
    ],
    "DOL": [
     18,
     25
    ],
    "SOU": [
     14,
     25
    ],
    "WST": [
     9,
     24
    ]
   },
   "rank": 1,
   "mv": "",
   "roundScore": 0,
   "totalScore": 135,
   "totalMargin": 492,
   "margins": [
    16,
    14,
    10,
    23,
    28,
    26,
    26,
    11,
    8,
    26,
    14,
    18,
    16,
    8,
    36,
    4,
    10,
    12,
    20,
    12,
    0,
    76,
    12,
    12,
    2,
    16,
    20,
    16,
    null
   ],
   "scores": [
    5,
    4,
    4,
    2,
    10,
    3,
    5,
    7,
    5,
    4,
    10,
    4,
    3,
    3,
    3,
    4,
    6,
    3,
    4,
    6,
    6,
    7,
    4,
    4,
    5,
    6,
    5,
    3,
    null
   ],
   "mpreds": [
    6,
    6,
    6,
    6,
    6,
    10,
    6,
    30,
    8,
    58,
    36,
    10,
    10,
    22,
    78,
    6,
    10,
    34,
    6,
    10,
    6,
    6,
    10,
    6,
    6,
    10,
    6,
    6,
    null
   ],
   "picks": {},
   "beh": {
    "a": 0.674,
    "b": 0.8356,
    "loy": 3.86,
    "n": 208,
    "hit": 0.7788
   }
  },
  {
   "name": "Brigitte",
   "me": true,
   "aff": {
    "NEW": [
     12,
     25
    ],
    "NQL": [
     15,
     25
    ],
    "CAN": [
     15,
     23
    ],
    "STI": [
     3,
     24
    ],
    "MEL": [
     10,
     24
    ],
    "PAR": [
     4,
     22
    ],
    "NZW": [
     23,
     25
    ],
    "SYD": [
     25,
     25
    ],
    "BRI": [
     5,
     23
    ],
    "PEN": [
     18,
     23
    ],
    "CRO": [
     15,
     25
    ],
    "GLD": [
     1,
     24
    ],
    "MAN": [
     15,
     24
    ],
    "CBR": [
     10,
     24
    ],
    "DOL": [
     17,
     25
    ],
    "SOU": [
     11,
     25
    ],
    "WST": [
     6,
     24
    ]
   },
   "rank": 2,
   "mv": "",
   "roundScore": 0,
   "totalScore": 133,
   "totalMargin": 476,
   "margins": [
    14,
    8,
    0,
    9,
    42,
    16,
    36,
    15,
    12,
    28,
    20,
    4,
    10,
    10,
    38,
    2,
    16,
    18,
    22,
    6,
    6,
    66,
    18,
    2,
    4,
    22,
    18,
    14,
    null
   ],
   "scores": [
    5,
    5,
    4,
    3,
    5,
    3,
    5,
    6,
    6,
    7,
    7,
    4,
    1,
    6,
    2,
    5,
    6,
    3,
    3,
    5,
    6,
    10,
    5,
    5,
    5,
    6,
    3,
    2,
    null
   ],
   "mpreds": [
    4,
    null,
    4,
    8,
    8,
    null,
    4,
    34,
    4,
    60,
    42,
    4,
    4,
    24,
    80,
    4,
    4,
    40,
    4,
    4,
    null,
    4,
    4,
    4,
    4,
    4,
    4,
    4,
    null
   ],
   "picks": {},
   "beh": {
    "a": 0.1022,
    "b": 1.3823,
    "loy": 3.973,
    "n": 205,
    "hit": 0.8195
   }
  },
  {
   "name": "Thorners69",
   "me": false,
   "aff": {
    "NEW": [
     10,
     25
    ],
    "NQL": [
     10,
     24
    ],
    "CAN": [
     10,
     24
    ],
    "STI": [
     5,
     24
    ],
    "MEL": [
     13,
     23
    ],
    "PAR": [
     6,
     24
    ],
    "NZW": [
     17,
     25
    ],
    "SYD": [
     22,
     25
    ],
    "BRI": [
     9,
     24
    ],
    "PEN": [
     20,
     24
    ],
    "CRO": [
     18,
     25
    ],
    "GLD": [
     6,
     23
    ],
    "MAN": [
     11,
     23
    ],
    "CBR": [
     15,
     24
    ],
    "DOL": [
     13,
     24
    ],
    "SOU": [
     12,
     25
    ],
    "WST": [
     8,
     24
    ]
   },
   "rank": 3,
   "mv": "",
   "roundScore": 0,
   "totalScore": 131,
   "totalMargin": 515,
   "margins": [
    20,
    23,
    2,
    9,
    34,
    26,
    40,
    13,
    8,
    26,
    14,
    16,
    16,
    6,
    32,
    8,
    12,
    30,
    18,
    10,
    2,
    60,
    22,
    2,
    8,
    18,
    22,
    18,
    null
   ],
   "scores": [
    4,
    6,
    4,
    3,
    4,
    3,
    5,
    6,
    6,
    6,
    5,
    3,
    4,
    6,
    2,
    4,
    6,
    4,
    5,
    7,
    6,
    7,
    5,
    5,
    4,
    6,
    4,
    1,
    null
   ],
   "mpreds": [
    10,
    15,
    2,
    8,
    null,
    10,
    8,
    32,
    8,
    58,
    36,
    8,
    10,
    20,
    74,
    10,
    8,
    8,
    8,
    8,
    4,
    10,
    null,
    4,
    null,
    8,
    8,
    8,
    null
   ],
   "picks": {},
   "beh": {
    "a": 0.3687,
    "b": 0.8876,
    "loy": 1.9944,
    "n": 205,
    "hit": 0.7024
   }
  },
  {
   "name": "Jake",
   "me": false,
   "aff": {
    "MEL": [
     13,
     24
    ],
    "PAR": [
     4,
     24
    ],
    "NZW": [
     19,
     25
    ],
    "SYD": [
     18,
     25
    ],
    "BRI": [
     8,
     24
    ],
    "PEN": [
     25,
     25
    ],
    "CRO": [
     15,
     25
    ],
    "GLD": [
     2,
     24
    ],
    "MAN": [
     12,
     23
    ],
    "CBR": [
     11,
     23
    ],
    "DOL": [
     15,
     23
    ],
    "SOU": [
     15,
     24
    ],
    "WST": [
     12,
     23
    ],
    "NQL": [
     12,
     24
    ],
    "STI": [
     2,
     22
    ],
    "NEW": [
     10,
     23
    ],
    "CAN": [
     9,
     23
    ]
   },
   "rank": 4,
   "mv": "",
   "roundScore": 0,
   "totalScore": 129,
   "totalMargin": 492,
   "margins": [
    10,
    35,
    2,
    2,
    48,
    26,
    36,
    11,
    22,
    12,
    10,
    8,
    22,
    14,
    34,
    2,
    6,
    6,
    10,
    20,
    8,
    66,
    6,
    20,
    0,
    4,
    30,
    22,
    null
   ],
   "scores": [
    4,
    6,
    6,
    3,
    5,
    2,
    5,
    7,
    5,
    6,
    6,
    3,
    3,
    6,
    3,
    3,
    6,
    3,
    4,
    4,
    6,
    10,
    5,
    3,
    4,
    6,
    4,
    1,
    null
   ],
   "mpreds": [
    null,
    27,
    2,
    15,
    14,
    10,
    4,
    30,
    6,
    44,
    32,
    null,
    16,
    null,
    76,
    null,
    14,
    28,
    16,
    18,
    14,
    4,
    16,
    14,
    8,
    22,
    16,
    12,
    null
   ],
   "picks": {},
   "beh": {
    "a": 0.5219,
    "b": 1.2355,
    "loy": 2.9482,
    "n": 202,
    "hit": 0.7723
   }
  },
  {
   "name": "Special unit",
   "me": false,
   "aff": {
    "NEW": [
     12,
     25
    ],
    "NQL": [
     13,
     25
    ],
    "CAN": [
     14,
     23
    ],
    "STI": [
     3,
     24
    ],
    "MEL": [
     15,
     24
    ],
    "PAR": [
     4,
     23
    ],
    "NZW": [
     17,
     25
    ],
    "SYD": [
     24,
     25
    ],
    "BRI": [
     8,
     23
    ],
    "PEN": [
     19,
     22
    ],
    "CRO": [
     16,
     24
    ],
    "GLD": [
     2,
     24
    ],
    "MAN": [
     13,
     23
    ],
    "CBR": [
     9,
     24
    ],
    "DOL": [
     12,
     23
    ],
    "SOU": [
     14,
     23
    ],
    "WST": [
     7,
     24
    ]
   },
   "rank": 5,
   "mv": "",
   "roundScore": 0,
   "totalScore": 126,
   "totalMargin": 506,
   "margins": [
    16,
    20,
    12,
    7,
    34,
    30,
    39,
    11,
    24,
    24,
    22,
    0,
    14,
    6,
    34,
    10,
    12,
    22,
    16,
    2,
    6,
    68,
    18,
    4,
    4,
    21,
    22,
    8,
    null
   ],
   "scores": [
    4,
    5,
    3,
    3,
    7,
    3,
    4,
    6,
    4,
    5,
    5,
    4,
    1,
    6,
    2,
    6,
    5,
    2,
    3,
    4,
    6,
    6,
    4,
    7,
    4,
    6,
    5,
    6,
    null
   ],
   "mpreds": [
    6,
    12,
    8,
    10,
    null,
    14,
    7,
    30,
    8,
    56,
    null,
    8,
    8,
    20,
    76,
    12,
    8,
    null,
    10,
    null,
    null,
    2,
    4,
    2,
    4,
    5,
    8,
    2,
    null
   ],
   "picks": {},
   "beh": {
    "a": 0.3334,
    "b": 0.9239,
    "loy": 3.5437,
    "n": 202,
    "hit": 0.7624
   }
  },
  {
   "name": "Susie loo",
   "me": false,
   "aff": {
    "NEW": [
     18,
     25
    ],
    "NQL": [
     14,
     25
    ],
    "CAN": [
     20,
     24
    ],
    "STI": [
     6,
     24
    ],
    "MEL": [
     7,
     24
    ],
    "PAR": [
     1,
     24
    ],
    "NZW": [
     12,
     25
    ],
    "SYD": [
     8,
     25
    ],
    "BRI": [
     6,
     24
    ],
    "PEN": [
     24,
     25
    ],
    "CRO": [
     11,
     25
    ],
    "GLD": [
     4,
     24
    ],
    "MAN": [
     24,
     24
    ],
    "CBR": [
     14,
     24
    ],
    "DOL": [
     16,
     25
    ],
    "SOU": [
     14,
     25
    ],
    "WST": [
     9,
     24
    ]
   },
   "rank": 6,
   "mv": "",
   "roundScore": 0,
   "totalScore": 114,
   "totalMargin": 541,
   "margins": [
    6,
    18,
    4,
    25,
    33,
    36,
    28,
    23,
    20,
    24,
    30,
    12,
    14,
    8,
    38,
    2,
    16,
    14,
    16,
    10,
    2,
    74,
    14,
    10,
    10,
    30,
    18,
    6,
    null
   ],
   "scores": [
    5,
    4,
    3,
    2,
    7,
    3,
    5,
    5,
    4,
    6,
    5,
    4,
    3,
    4,
    2,
    3,
    7,
    2,
    3,
    5,
    5,
    4,
    4,
    3,
    5,
    4,
    4,
    3,
    null
   ],
   "mpreds": [
    16,
    10,
    0,
    8,
    1,
    20,
    4,
    4,
    4,
    56,
    8,
    4,
    8,
    22,
    80,
    4,
    4,
    36,
    10,
    8,
    4,
    4,
    8,
    4,
    18,
    4,
    4,
    4,
    null
   ],
   "picks": {},
   "beh": {
    "a": 0.4488,
    "b": 0.338,
    "loy": 5.0671,
    "n": 208,
    "hit": 0.8173
   }
  }
 ]
};
